import type { Assessment, Severity } from "@/types";
import { assessmentProgress } from "@/store/assessments";
import { getPhase } from "@/content/phases";
import { formatDate, formatTime } from "./utils";

const envLabel: Record<string, string> = {
  htb: "Hack The Box",
  thm: "TryHackMe",
  ctf: "CTF",
  personal: "Personal Lab",
  authorized: "Authorized Penetration Test",
  other: "Other",
};

const sevOrder: Record<Severity, number> = { critical: 0, high: 1, medium: 2, low: 3, info: 4 };

/**
 * Build a professional Markdown report from ACTUAL assessment data (spec §47).
 * Never invents missing information — absent sections are marked accordingly.
 */
export function generateReport(a: Assessment): string {
  const phase = getPhase(a.currentPhase);
  const openPorts = a.services.filter((s) => s.status === "open");
  const findings = [...a.findings].sort((x, y) => sevOrder[x.severity] - sevOrder[y.severity]);
  const counts = findings.reduce<Record<string, number>>((acc, f) => {
    acc[f.severity] = (acc[f.severity] ?? 0) + 1;
    return acc;
  }, {});

  const L: string[] = [];
  const target = a.asset.ip || a.asset.hostname || a.asset.domain || "N/A";

  // Cover
  L.push(`# Penetration Test Report`, ``);
  L.push(`**Assessment:** ${a.name}`);
  L.push(`**Target:** ${target}`);
  L.push(`**Environment:** ${envLabel[a.environment] ?? a.environment}`);
  L.push(`**Date:** ${formatDate(a.createdAt)}`);
  L.push(`**Current phase:** ${phase.label} (${assessmentProgress(a)}% through lifecycle)`);
  L.push(``, `> Report generated by T3st3r from recorded assessment data. Findings reflect only what was observed and recorded.`, ``);
  L.push(`---`, ``);

  // Executive summary
  L.push(`## Executive Summary`, ``);
  if (findings.length) {
    const crit = counts.critical ?? 0;
    const high = counts.high ?? 0;
    L.push(
      `This assessment of ${target} identified ${findings.length} finding${findings.length === 1 ? "" : "s"}` +
        (crit || high ? `, including ${crit} critical and ${high} high-severity issue${crit + high === 1 ? "" : "s"}.` : ".")
    );
  } else {
    L.push(`No findings have been recorded for this assessment yet.`);
  }
  L.push(``);

  // Scope
  L.push(`## Scope`, ``);
  L.push(`- **Authorized target(s):** ${a.scope.authorizedTargets || target}`);
  if (a.scope.allowedIps) L.push(`- **Allowed IPs:** ${a.scope.allowedIps}`);
  if (a.scope.allowedDomains) L.push(`- **Allowed domains:** ${a.scope.allowedDomains}`);
  if (a.scope.exclusions) L.push(`- **Exclusions:** ${a.scope.exclusions}`);
  if (a.scope.constraints) L.push(`- **Constraints:** ${a.scope.constraints}`);
  L.push(`- **Authorization confirmed:** ${a.scope.authorized ? "Yes" : "No"}`);
  L.push(``);

  // Methodology
  L.push(`## Methodology`, ``);
  L.push(
    `Testing followed a standard lifecycle (reconnaissance, scanning, enumeration, vulnerability analysis, validation, exploitation, post-exploitation, and reporting), aligned with PTES and NIST SP 800-115. Commands were executed manually by the tester; results were interpreted and recorded throughout.`,
    ``
  );

  // Attack surface / assets
  L.push(`## Attack Surface`, ``);
  L.push(`- **Host:** ${target}`);
  if (a.asset.os && a.asset.os !== "unknown") L.push(`- **Operating system:** ${a.asset.os}`);
  if (openPorts.length) {
    L.push(`- **Open services:**`);
    for (const s of openPorts) {
      L.push(`  - \`${s.port}/${s.protocol}\` ${s.service}${s.version ? ` — ${s.version}` : ""}`);
    }
  } else {
    L.push(`- **Open services:** none recorded`);
  }
  L.push(``);

  // Findings
  L.push(`## Findings`, ``);
  if (!findings.length) {
    L.push(`_No findings recorded._`, ``);
  } else {
    findings.forEach((f, i) => {
      L.push(`### ${i + 1}. ${f.title}`, ``);
      L.push(`- **Severity:** ${f.severity.toUpperCase()}`);
      L.push(`- **Status:** ${f.status}`);
      if (f.asset) L.push(`- **Affected asset:** ${f.asset}`);
      L.push(``);
      if (f.description) L.push(`**Description**`, ``, f.description, ``);
      if (f.reproduction) L.push(`**Reproduction**`, ``, "```", f.reproduction, "```", ``);
      if (f.evidence) L.push(`**Evidence**`, ``, "```", f.evidence, "```", ``);
      if (f.impact) L.push(`**Impact**`, ``, f.impact, ``);
      if (f.remediation) L.push(`**Remediation**`, ``, f.remediation, ``);
      if (f.references?.length) L.push(`**References**`, ``, ...f.references.map((r) => `- ${r}`), ``);
      L.push(`---`, ``);
    });
  }

  // Risk summary
  L.push(`## Risk Summary`, ``);
  if (findings.length) {
    L.push(`| Severity | Count |`, `| --- | --- |`);
    (["critical", "high", "medium", "low", "info"] as Severity[]).forEach((s) => {
      if (counts[s]) L.push(`| ${s[0].toUpperCase() + s.slice(1)} | ${counts[s]} |`);
    });
  } else {
    L.push(`No findings to summarize.`);
  }
  L.push(``);

  // Timeline
  if (a.timeline.length) {
    L.push(`## Timeline`, ``);
    [...a.timeline]
      .sort((x, y) => new Date(x.timestamp).getTime() - new Date(y.timestamp).getTime())
      .forEach((e) => {
        L.push(`- ${formatDate(e.timestamp)} ${formatTime(e.timestamp)} — ${e.label}${e.detail ? ` (${e.detail})` : ""}`);
      });
    L.push(``);
  }

  // Evidence appendix
  if (a.evidence.length) {
    L.push(`## Appendix: Evidence`, ``);
    a.evidence.forEach((e, i) => {
      L.push(`### E${i + 1}. ${e.title} (${e.kind})`, ``, "```", e.content, "```", ``);
    });
  }

  // Notes appendix
  const relevantNotes = a.notes.filter((n) => n.type !== "todo");
  if (relevantNotes.length) {
    L.push(`## Appendix: Tester Notes`, ``);
    relevantNotes.forEach((n) => L.push(`- **[${n.type}]** ${n.content}`));
    L.push(``);
  }

  L.push(`## Conclusion`, ``);
  L.push(
    findings.length
      ? `The issues above should be remediated according to their severity. This report reflects the state of the assessment at time of generation.`
      : `No findings were recorded at time of generation. Continue enumeration and validation, then regenerate this report.`,
    ``
  );

  return L.join("\n");
}
