import type { PortMapping } from "@/types";

/**
 * Port knowledge base (spec §19, §50). Drives Port Lookup, the decision engine,
 * and the "next step" suggestions from the Nmap parser.
 * serviceModuleId links to a full teacher module where one exists.
 */
export const PORTS: PortMapping[] = [
  {
    port: 21,
    protocol: "tcp",
    service: "FTP",
    serviceModuleId: "ftp",
    os: "any",
    summary: "File Transfer Protocol. Often allows anonymous access or leaks a banner/version.",
    investigate: [
      "Try anonymous login (user: anonymous)",
      "Grab the version banner — some FTP daemons have known issues",
      "Check for writable directories and whether files are web-served elsewhere",
    ],
    commands: ["nmap -p21 -sV -sC <TARGET>", "ftp <TARGET>", "curl ftp://<TARGET>/ --user anonymous:anonymous"],
    nextSteps: ["FTP enumeration", "Check if uploaded files are reachable via HTTP"],
    relatedLessons: ["svc-ftp"],
    keywords: ["ftp", "anonymous", "file transfer", "vsftpd", "proftpd"],
  },
  {
    port: 22,
    protocol: "tcp",
    service: "SSH",
    serviceModuleId: "ssh",
    os: "any",
    summary: "Secure Shell. Remote administration. The banner reveals the implementation/version.",
    investigate: [
      "Read the version banner (OpenSSH x.y)",
      "Note supported auth methods (password vs key-only)",
      "Do NOT brute force blindly — think about lockouts and noise",
    ],
    commands: ["nmap -p22 -sV <TARGET>", "ssh <USER>@<TARGET>", "ssh-audit <TARGET>"],
    nextSteps: ["SSH enumeration", "If you find creds elsewhere, try them here"],
    relatedLessons: ["svc-ssh"],
    keywords: ["ssh", "openssh", "remote", "key", "22"],
  },
  {
    port: 23,
    protocol: "tcp",
    service: "Telnet",
    os: "any",
    summary: "Legacy cleartext remote administration. Its presence is itself a finding.",
    investigate: ["Grab banner", "Cleartext protocol — credentials transit unencrypted", "Try default creds on lab devices"],
    commands: ["nmap -p23 -sV <TARGET>", "telnet <TARGET> 23"],
    nextSteps: ["Note weak/legacy service as a finding", "Look for default credentials"],
    keywords: ["telnet", "cleartext", "legacy"],
  },
  {
    port: 25,
    protocol: "tcp",
    service: "SMTP",
    os: "any",
    summary: "Mail transfer. Can leak usernames via VRFY/EXPN and reveal internal hostnames.",
    investigate: ["Banner + hostname", "VRFY/EXPN user enumeration (often disabled)", "Open relay testing (authorized only)"],
    commands: ["nmap -p25 --script smtp-commands,smtp-enum-users <TARGET>", "nc <TARGET> 25"],
    nextSteps: ["Username harvesting feeds password attacks elsewhere"],
    keywords: ["smtp", "mail", "vrfy", "expn", "relay"],
  },
  {
    port: 53,
    protocol: "tcp/udp",
    service: "DNS",
    serviceModuleId: "dns",
    os: "any",
    summary: "Domain Name System. May allow zone transfers and reveals internal names.",
    investigate: [
      "Attempt a zone transfer (AXFR) — often the fastest win",
      "Reverse lookups for the subnet",
      "In AD, DNS often runs on the domain controller",
    ],
    commands: ["dig axfr @<TARGET> <DOMAIN>", "dnsenum <DOMAIN>", "nslookup"],
    nextSteps: ["Discovered hostnames become new targets", "In AD, pivot to LDAP/Kerberos on the DC"],
    relatedLessons: ["svc-dns", "recon-dns"],
    keywords: ["dns", "axfr", "zone transfer", "dig", "53"],
  },
  {
    port: 80,
    protocol: "tcp",
    service: "HTTP",
    serviceModuleId: "http",
    os: "any",
    summary: "Web server. Usually the richest attack surface — apps, endpoints, logins, APIs.",
    investigate: [
      "Identify server + framework (headers, whatweb)",
      "Read robots.txt, sitemap.xml, and page source",
      "Content discovery (directories/files) with a good wordlist",
      "Map authentication and any API endpoints",
    ],
    commands: [
      "curl -I http://<TARGET>",
      "whatweb http://<TARGET>",
      "ffuf -u http://<TARGET>/FUZZ -w /usr/share/seclists/Discovery/Web-Content/directory-list-2.3-medium.txt",
    ],
    nextSteps: ["Start the Web Enumeration workflow"],
    relatedLessons: ["svc-http", "web-methodology", "web-content-discovery"],
    keywords: ["http", "web", "80", "apache", "nginx", "iis"],
  },
  {
    port: 88,
    protocol: "tcp",
    service: "Kerberos",
    os: "windows",
    summary: "Kerberos authentication — a strong signal this host is an Active Directory Domain Controller.",
    investigate: ["Confirm DC role (usually 53/88/389/445 together)", "Enumerate users for AS-REP roasting", "Kerberoast service accounts if you have any creds"],
    commands: ["nmap -p88 <TARGET>", "nxc smb <TARGET>", "GetNPUsers.py <DOMAIN>/ -usersfile users.txt -no-pass"],
    nextSteps: ["Move into the Active Directory workflow"],
    relatedLessons: ["ad-kerberos"],
    keywords: ["kerberos", "88", "domain controller", "ad", "asrep"],
  },
  {
    port: 110,
    protocol: "tcp",
    service: "POP3",
    os: "any",
    summary: "Mailbox retrieval. Cleartext unless POP3S. Creds may be reused elsewhere.",
    investigate: ["Banner", "Login with discovered creds", "Read mail for further credentials/info"],
    commands: ["nmap -p110 -sV <TARGET>", "nc <TARGET> 110"],
    nextSteps: ["Credential reuse checks"],
    keywords: ["pop3", "mail", "110"],
  },
  {
    port: 111,
    protocol: "tcp/udp",
    service: "RPCbind / NFS",
    os: "linux",
    summary: "ONC RPC portmapper — frequently fronts NFS. Look for exported shares.",
    investigate: ["List RPC services", "Enumerate NFS exports", "Mount world-readable/writable exports (lab)"],
    commands: ["rpcinfo -p <TARGET>", "showmount -e <TARGET>", "nmap -p111 --script nfs-ls,nfs-showmount <TARGET>"],
    nextSteps: ["Mounted exports may contain credentials or SSH keys"],
    keywords: ["rpc", "nfs", "111", "showmount", "exports"],
  },
  {
    port: 135,
    protocol: "tcp",
    service: "MSRPC",
    os: "windows",
    summary: "Windows RPC endpoint mapper. Often paired with 139/445 on Windows hosts.",
    investigate: ["Enumerate RPC endpoints", "Combine with SMB enumeration"],
    commands: ["rpcdump.py <TARGET>", "nmap -p135 <TARGET>"],
    nextSteps: ["SMB enumeration", "In AD, RPC can enumerate users/groups"],
    keywords: ["msrpc", "135", "windows", "rpc"],
  },
  {
    port: 139,
    protocol: "tcp",
    service: "NetBIOS / SMB",
    serviceModuleId: "smb",
    os: "windows",
    summary: "NetBIOS session service — legacy SMB transport. Treat with 445 as SMB.",
    investigate: ["NetBIOS name enumeration", "Same checks as SMB/445"],
    commands: ["nmblookup -A <TARGET>", "nxc smb <TARGET>"],
    nextSteps: ["SMB enumeration"],
    relatedLessons: ["svc-smb"],
    keywords: ["netbios", "139", "smb"],
  },
  {
    port: 143,
    protocol: "tcp",
    service: "IMAP",
    os: "any",
    summary: "Mailbox access protocol. Cleartext unless IMAPS. Creds may be reused.",
    investigate: ["Banner", "Login with discovered creds"],
    commands: ["nmap -p143 -sV <TARGET>", "nc <TARGET> 143"],
    nextSteps: ["Credential reuse checks"],
    keywords: ["imap", "mail", "143"],
  },
  {
    port: 161,
    protocol: "udp",
    service: "SNMP",
    os: "any",
    summary: "Network management over UDP. Weak community strings ('public') leak huge amounts of data.",
    investigate: ["Try community strings (public/private)", "Walk the MIB for users, processes, software, routes"],
    commands: ["snmpwalk -v2c -c public <TARGET>", "onesixtyone -c community.txt <TARGET>"],
    nextSteps: ["SNMP data often reveals usernames, software versions, and network layout"],
    keywords: ["snmp", "161", "community", "public", "snmpwalk"],
  },
  {
    port: 389,
    protocol: "tcp",
    service: "LDAP",
    serviceModuleId: "ldap",
    os: "windows",
    summary: "Directory service. In AD, LDAP exposes users, groups, computers, and policies.",
    investigate: ["Anonymous bind to read the directory", "Enumerate naming context, users, groups", "Feed data into BloodHound"],
    commands: ["ldapsearch -x -H ldap://<TARGET> -s base namingcontexts", "nxc ldap <TARGET> -u '' -p ''"],
    nextSteps: ["Active Directory workflow"],
    relatedLessons: ["svc-ldap", "ad-ldap"],
    keywords: ["ldap", "389", "directory", "ad", "bind"],
  },
  {
    port: 443,
    protocol: "tcp",
    service: "HTTPS",
    serviceModuleId: "http",
    os: "any",
    summary: "HTTP over TLS. Same web attack surface as 80, plus certificate metadata.",
    investigate: ["Inspect the TLS certificate — SANs often reveal hostnames", "Everything from the HTTP workflow", "Check for HTTP/2, vhosts"],
    commands: ["curl -Ik https://<TARGET>", "openssl s_client -connect <TARGET>:443", "whatweb https://<TARGET>"],
    nextSteps: ["Web Enumeration workflow", "Certificate SANs → new vhosts/subdomains"],
    relatedLessons: ["svc-http", "web-methodology"],
    keywords: ["https", "443", "tls", "ssl", "certificate"],
  },
  {
    port: 445,
    protocol: "tcp",
    service: "SMB",
    serviceModuleId: "smb",
    os: "windows",
    summary: "Server Message Block — file shares, and in AD a primary enumeration & auth surface.",
    investigate: [
      "List shares, try null/guest sessions",
      "Grab OS/domain/signing info",
      "With creds: spider shares, run RID cycling, check for admin access",
    ],
    commands: [
      "nxc smb <TARGET>",
      "nxc smb <TARGET> -u '' -p '' --shares",
      "smbclient -N -L //<TARGET>/",
      "enum4linux-ng -A <TARGET>",
    ],
    nextSteps: ["SMB enumeration", "In AD → Active Directory workflow"],
    relatedLessons: ["svc-smb", "ad-smb"],
    keywords: ["smb", "445", "shares", "netexec", "smbclient", "microsoft-ds"],
  },
  {
    port: 465,
    protocol: "tcp",
    service: "SMTPS",
    os: "any",
    summary: "SMTP over TLS.",
    investigate: ["Banner + TLS cert", "Same checks as SMTP"],
    commands: ["nmap -p465 -sV <TARGET>"],
    nextSteps: ["SMTP enumeration"],
    keywords: ["smtps", "465", "mail"],
  },
  {
    port: 636,
    protocol: "tcp",
    service: "LDAPS",
    serviceModuleId: "ldap",
    os: "windows",
    summary: "LDAP over TLS. Same directory surface as 389 with encryption.",
    investigate: ["Directory enumeration over TLS", "Certificate details"],
    commands: ["ldapsearch -x -H ldaps://<TARGET>"],
    nextSteps: ["Active Directory workflow"],
    keywords: ["ldaps", "636", "ad"],
  },
  {
    port: 1433,
    protocol: "tcp",
    service: "MSSQL",
    serviceModuleId: "mssql",
    os: "windows",
    summary: "Microsoft SQL Server. Weak creds, xp_cmdshell, and impersonation are classic paths.",
    investigate: ["Try sa/weak creds", "Enumerate databases", "Check xp_cmdshell / linked servers (authorized)"],
    commands: ["nxc mssql <TARGET> -u <USER> -p <PASS>", "impacket-mssqlclient <USER>@<TARGET>"],
    nextSteps: ["Database enumeration → potential command execution"],
    relatedLessons: ["svc-mssql"],
    keywords: ["mssql", "1433", "sqlserver", "sa", "xp_cmdshell"],
  },
  {
    port: 1521,
    protocol: "tcp",
    service: "Oracle TNS",
    os: "any",
    summary: "Oracle database listener. SID enumeration and default creds are common starting points.",
    investigate: ["Enumerate SIDs", "Default account testing (authorized)"],
    commands: ["nmap -p1521 --script oracle-sid-brute <TARGET>", "odat all -s <TARGET>"],
    nextSteps: ["Database enumeration"],
    keywords: ["oracle", "1521", "tns", "sid"],
  },
  {
    port: 2049,
    protocol: "tcp",
    service: "NFS",
    os: "linux",
    summary: "Network File System. Exports may be mountable and world-writable.",
    investigate: ["List exports", "Mount and inspect for secrets/keys", "no_root_squash abuse (lab privesc)"],
    commands: ["showmount -e <TARGET>", "mount -t nfs <TARGET>:/export /mnt/nfs"],
    nextSteps: ["Look for SSH keys, config with credentials"],
    keywords: ["nfs", "2049", "exports", "mount"],
  },
  {
    port: 3306,
    protocol: "tcp",
    service: "MySQL",
    serviceModuleId: "mysql",
    os: "any",
    summary: "MySQL/MariaDB database. Look for weak/blank root, remote access, and readable data.",
    investigate: ["Try root with blank/weak password", "Enumerate databases and users", "Read files via LOAD_FILE (privilege dependent)"],
    commands: ["mysql -h <TARGET> -u root -p", "nmap -p3306 --script mysql-info,mysql-empty-password <TARGET>"],
    nextSteps: ["Database enumeration → credentials for other services"],
    relatedLessons: ["svc-mysql"],
    keywords: ["mysql", "mariadb", "3306", "database"],
  },
  {
    port: 3389,
    protocol: "tcp",
    service: "RDP",
    serviceModuleId: "rdp",
    os: "windows",
    summary: "Remote Desktop. With valid creds it is often direct interactive access.",
    investigate: ["Check NLA requirement", "Try discovered credentials (mind lockouts)", "BlueKeep-era hosts are rare but note the version"],
    commands: ["nxc rdp <TARGET> -u <USER> -p <PASS>", "xfreerdp /u:<USER> /p:<PASS> /v:<TARGET>"],
    nextSteps: ["Interactive Windows access → post-exploitation"],
    relatedLessons: ["svc-rdp"],
    keywords: ["rdp", "3389", "remote desktop", "xfreerdp"],
  },
  {
    port: 5432,
    protocol: "tcp",
    service: "PostgreSQL",
    os: "any",
    summary: "PostgreSQL database. Weak creds and COPY ... PROGRAM can lead to command execution.",
    investigate: ["Try postgres/weak creds", "Enumerate databases", "COPY FROM PROGRAM for RCE (authorized, privilege dependent)"],
    commands: ["psql -h <TARGET> -U postgres", "nxc postgres <TARGET> -u postgres -p postgres"],
    nextSteps: ["Database enumeration"],
    keywords: ["postgres", "postgresql", "5432", "database"],
  },
  {
    port: 5985,
    protocol: "tcp",
    service: "WinRM (HTTP)",
    serviceModuleId: "winrm",
    os: "windows",
    summary: "Windows Remote Management. With valid creds, evil-winrm gives a clean shell.",
    investigate: ["Check if creds grant WinRM access", "Members of Remote Management Users / Administrators"],
    commands: ["nxc winrm <TARGET> -u <USER> -p <PASS>", "evil-winrm -i <TARGET> -u <USER> -p <PASS>"],
    nextSteps: ["Interactive Windows shell → post-exploitation"],
    relatedLessons: ["svc-winrm"],
    keywords: ["winrm", "5985", "evil-winrm", "remote management"],
  },
  {
    port: 5986,
    protocol: "tcp",
    service: "WinRM (HTTPS)",
    serviceModuleId: "winrm",
    os: "windows",
    summary: "WinRM over TLS.",
    investigate: ["Same as 5985 with TLS"],
    commands: ["evil-winrm -i <TARGET> -u <USER> -p <PASS> -S"],
    nextSteps: ["Interactive Windows shell"],
    keywords: ["winrm", "5986", "https"],
  },
  {
    port: 6379,
    protocol: "tcp",
    service: "Redis",
    os: "any",
    summary: "In-memory data store. Frequently unauthenticated — can lead to file write / RCE.",
    investigate: ["Connect unauthenticated", "INFO/CONFIG GET dir", "Write SSH keys or web shells where the path allows (authorized)"],
    commands: ["redis-cli -h <TARGET>", "nmap -p6379 --script redis-info <TARGET>"],
    nextSteps: ["Config disclosure → potential file write"],
    keywords: ["redis", "6379", "nosql"],
  },
  {
    port: 8080,
    protocol: "tcp",
    service: "HTTP (alt)",
    serviceModuleId: "http",
    os: "any",
    summary: "Alternate web port — proxies, app servers, Tomcat, Jenkins, dashboards.",
    investigate: ["Fingerprint the app (Tomcat manager? Jenkins? a proxy?)", "Default creds on management consoles", "Full web enumeration"],
    commands: ["curl -I http://<TARGET>:8080", "whatweb http://<TARGET>:8080"],
    nextSteps: ["Web Enumeration workflow", "Tomcat/Jenkins have specific known paths"],
    relatedLessons: ["svc-http"],
    keywords: ["8080", "tomcat", "jenkins", "proxy", "http-alt"],
  },
  {
    port: 27017,
    protocol: "tcp",
    service: "MongoDB",
    os: "any",
    summary: "NoSQL database. Older/default deployments allow unauthenticated access.",
    investigate: ["Connect unauthenticated", "List databases and collections"],
    commands: ["mongosh --host <TARGET>", "nmap -p27017 --script mongodb-info <TARGET>"],
    nextSteps: ["Data may contain credentials/PII"],
    keywords: ["mongodb", "27017", "nosql"],
  },
];

export const PORT_MAP: Record<number, PortMapping> = Object.fromEntries(
  PORTS.map((p) => [p.port, p])
);

/** Look up a port, including altPorts. */
export function lookupPort(port: number): PortMapping | undefined {
  return PORTS.find((p) => p.port === port || p.altPorts?.includes(port));
}
