import type { Lesson } from "@/types";

export const reconLessons: Lesson[] = [
  {
    id: "recon-dns",
    title: "DNS Reconnaissance",
    category: "recon",
    categoryLabel: "Reconnaissance",
    difficulty: "beginner",
    summary: "Turn a domain into a map of hosts using lookups, zone transfers, and subdomain discovery.",
    estMinutes: 8,
    methodology: ["PTES: Intelligence Gathering", "OSINT"],
    objectives: ["Resolve and reverse-resolve", "Attempt a zone transfer", "Discover subdomains passively and actively"],
    teacherIntro:
      "Before we scan ports, let's understand names. DNS often reveals the shape of an organization: mail servers, dev environments, and internal-sounding hosts. Sometimes a single misconfiguration hands us the entire zone.",
    why: "Every new hostname is a potential new target and a new attack surface. DNS is cheap, quiet, and frequently productive.",
    commands: [
      {
        id: "recon-dig-any",
        command: "dig <DOMAIN> ANY +noall +answer",
        platform: "any",
        purpose: "Pull the common records for a domain.",
        why: "A quick overview of A/MX/NS/TXT records orients you before deeper work.",
        lookFor: ["MX (mail)", "NS (name servers)", "TXT (SPF/verification, sometimes leaks)"],
        risk: "low",
        tags: ["dns", "dig"],
      },
      {
        id: "recon-axfr",
        command: "dig axfr @<NS> <DOMAIN>",
        platform: "any",
        purpose: "Attempt a zone transfer against a name server.",
        why: "If misconfigured, this dumps every record — the fastest possible enumeration.",
        exampleOutput: "dev.<DOMAIN>.   IN A 10.10.10.20\nvpn.<DOMAIN>.   IN A 10.10.10.30",
        lookFor: ["Full record dump", "Interesting internal names"],
        commonMistakes: ["Only trying one NS — try them all"],
        risk: "low",
        tags: ["dns", "axfr"],
      },
      {
        id: "recon-subfinder",
        command: "subfinder -d <DOMAIN> -silent | httpx -silent",
        platform: "kali",
        purpose: "Passively enumerate subdomains, then probe which are live web hosts.",
        why: "Passive sources (certs, search engines) find subdomains without touching the target; httpx confirms which respond.",
        lookFor: ["Live subdomains", "Unusual hosts (dev, staging, admin)"],
        risk: "low",
        tags: ["dns", "subfinder", "httpx", "subdomains"],
      },
    ],
    lookFor: ["Zone transfer success", "Subdomains and internal hostnames", "Mail/NS infrastructure"],
    branches: [
      { condition: "You discovered new hostnames", outcome: "Add them to /etc/hosts and scan the interesting ones.", goto: { type: "lesson", id: "scan-nmap-basics" } },
    ],
    commonMistakes: ["Skipping DNS entirely and only scanning the given IP"],
    next: ["recon-passive-active", "scan-nmap-basics"],
    related: ["svc-dns"],
    keywords: ["dns", "recon", "subdomain", "axfr", "dig", "subfinder"],
  },
  {
    id: "recon-passive-active",
    title: "Passive vs Active Reconnaissance",
    category: "recon",
    categoryLabel: "Reconnaissance",
    difficulty: "beginner",
    summary: "The difference between observing without touching (passive) and interacting directly (active) — and when each is appropriate.",
    estMinutes: 6,
    objectives: ["Distinguish passive from active recon", "Know what each reveals", "Understand the noise/authorization tradeoff"],
    teacherIntro:
      "Passive recon uses third-party data — certificate transparency, DNS, search engines — so the target never sees you. Active recon touches the target directly. Both are useful; the difference is footprint.",
    why: "On real engagements, footprint and authorization matter. Knowing which technique touches the target keeps you within scope and lets you stay quiet when needed.",
    notes: [
      { heading: "Passive sources", body: "crt.sh (certificate transparency), Shodan, DNS history, WHOIS, public repositories, and document metadata. None of these send packets to the target." },
      { heading: "Active techniques", body: "Port scans, banner grabbing, content discovery, and service enumeration all interact with the target directly and are visible in its logs." },
      { heading: "Certificate transparency is gold", body: "crt.sh lists certificates issued for a domain — a rich, passive source of subdomains including internal-sounding ones.", tone: "tip" },
    ],
    lookFor: ["Which technique touches the target", "What footprint each leaves"],
    exercise: {
      id: "rpa-ex",
      prompt: "You want subdomains but must stay completely off the target for now. Which do you use?",
      options: ["nmap against the whole subnet", "crt.sh / certificate transparency", "ffuf vhost brute forcing", "Directory discovery on the web app"],
      answerIndex: 1,
      explanation: "Certificate transparency (crt.sh) is fully passive — you query public CA logs, not the target. The other three all send traffic to the target and are active techniques.",
    },
    next: ["recon-dns"],
    keywords: ["passive", "active", "recon", "osint", "crt.sh", "certificate transparency"],
  },
  {
    id: "recon-whois",
    title: "WHOIS and Ownership Mapping",
    category: "recon",
    categoryLabel: "Reconnaissance",
    difficulty: "beginner",
    summary: "Identify who owns a domain or IP range and use that to scope and correlate assets.",
    estMinutes: 4,
    objectives: ["Query WHOIS for domains and IPs", "Identify netblocks/ASNs", "Correlate related assets"],
    teacherIntro:
      "WHOIS tells you who registered a domain or who owns an IP range. On real engagements this helps confirm scope and find related infrastructure; on labs it's usually minimal but still worth a glance.",
    why: "Ownership data helps you avoid touching out-of-scope assets and can reveal an organization's broader footprint (adjacent netblocks, related domains).",
    commands: [
      { id: "recon-whois-cmd", command: "whois <DOMAIN>", platform: "any", purpose: "Look up domain registration details.", why: "Registrant, dates, and name servers orient your recon.", lookFor: ["Registrar/registrant", "Name servers", "Creation/expiry dates"], risk: "low", tags: ["whois", "recon"] },
      { id: "recon-whois-ip", command: "whois <TARGET>", platform: "any", purpose: "Look up which organization owns an IP.", why: "Confirms an IP belongs to the in-scope org and reveals the netblock.", lookFor: ["OrgName / netblock (CIDR)", "Abuse contacts"], risk: "low", tags: ["whois", "ip", "asn"] },
    ],
    lookFor: ["Owning organization", "Netblock / ASN", "Related domains"],
    commonMistakes: ["Treating WHOIS privacy-protected data as a dead end — pivot to certs/DNS"],
    next: ["recon-dns", "recon-passive-active"],
    keywords: ["whois", "asn", "ownership", "netblock", "recon"],
  },
];
