import type { Lesson } from "@/types";

export const scanningLessons: Lesson[] = [
  {
    id: "scan-nmap-basics",
    title: "Nmap: The Sensible First Scan",
    category: "scanning",
    categoryLabel: "Scanning",
    difficulty: "beginner",
    summary: "The default -sC -sV scan, what each flag does, and how to read the result instead of drowning in it.",
    estMinutes: 9,
    methodology: ["PTES: Vulnerability Analysis", "NIST SP 800-115"],
    objectives: ["Run a version+script scan", "Understand the core flags", "Read output and pick a next service"],
    teacherIntro:
      "Nmap is the tool you'll run first on almost every box. But the goal isn't 'run nmap' — it's 'scan, then read, then decide'. We start with a balanced default that tells us what's listening and what version it is.",
    why: "The open ports and versions are your entire attack surface. A careful read of one good scan beats ten aggressive scans you never analyze.",
    commands: [
      {
        id: "scan-default",
        command: "nmap -sC -sV -oA nmap_initial <TARGET>",
        platform: "any",
        purpose: "Default scripts + version detection on the top 1000 TCP ports.",
        why: "Balanced first pass: identifies services and versions, runs safe default scripts, and saves output for later.",
        flags: [
          { flag: "-sC", meaning: "Default NSE scripts (safe, informative)" },
          { flag: "-sV", meaning: "Probe for service/version" },
          { flag: "-oA", meaning: "Save normal/greppable/XML output" },
          { flag: "-Pn", meaning: "Skip host discovery (add if ICMP is filtered)" },
        ],
        exampleOutput:
          "PORT     STATE SERVICE       VERSION\n22/tcp   open  ssh           OpenSSH 8.2p1 Ubuntu 4ubuntu0.5\n80/tcp   open  http          Apache httpd 2.4.41 ((Ubuntu))\n445/tcp  open  microsoft-ds  Samba smbd 4.6.2",
        lookFor: ["Open ports + service names", "Version strings", "Script output (titles, anonymous access)"],
        commonMistakes: ["Not saving output", "Assuming the default 1000 ports is everything"],
        risk: "low",
        next: "Kick off a full-port scan in the background, then enumerate the most promising service.",
        tags: ["nmap", "scan", "sV", "sC"],
      },
    ],
    lookFor: ["Which services are open", "Versions that hint at the OS", "Anything unusual on a non-standard port"],
    branches: [
      { condition: "You see web ports", outcome: "Go enumerate HTTP.", goto: { type: "service", id: "http" } },
      { condition: "You see only a couple of ports", outcome: "Run a full-port scan — the interesting service may be higher up.", goto: { type: "lesson", id: "scan-full-port" } },
    ],
    exercise: {
      id: "snb-ex",
      prompt: "Your -sC -sV scan finishes and shows only 22 and 80. What's the most useful next action?",
      options: [
        "Immediately launch Metasploit against SSH",
        "Start a full-port scan (-p-) to make sure you're not missing a service",
        "Give up — two ports is nothing",
        "Rescan the top 1000 ports again",
      ],
      answerIndex: 1,
      explanation:
        "The default scan only covers the top 1000 ports. Many boxes hide their key service on a high port. Start a full-port scan (-p-) to be sure, and meanwhile enumerate the web app you already found. Rescanning the same 1000 ports adds nothing.",
    },
    next: ["scan-full-port", "scan-interpreting"],
    keywords: ["nmap", "scan", "sC", "sV", "ports"],
  },
  {
    id: "scan-full-port",
    title: "Full-Port and Targeted Follow-up Scans",
    category: "scanning",
    categoryLabel: "Scanning",
    difficulty: "beginner",
    summary: "Find everything with -p-, then run a focused deep scan on just the open ports.",
    estMinutes: 7,
    objectives: ["Scan all 65535 ports efficiently", "Follow up with a focused version scan", "Balance speed vs completeness"],
    teacherIntro:
      "The default scan is a fast first look, not the final word. To be thorough we sweep all 65535 ports, then run a detailed scan against only the ports we found open. Two passes: fast-and-wide, then slow-and-deep.",
    why: "Boxes routinely place the real service on a high, non-standard port. Missing it means missing the whole path. The two-pass approach is both thorough and efficient.",
    commands: [
      {
        id: "scan-allports",
        command: "nmap -p- --min-rate 2000 -oA nmap_allports <TARGET>",
        platform: "any",
        purpose: "Scan every TCP port quickly to find all open ones.",
        why: "Covers the full range so nothing hides on a high port; --min-rate keeps it fast.",
        flags: [
          { flag: "-p-", meaning: "All 65535 ports" },
          { flag: "--min-rate 2000", meaning: "Send at least 2000 packets/sec (tune for the network)" },
        ],
        lookFor: ["Open ports outside the top 1000", "Unexpected high-port services"],
        risk: "low",
        next: "Take the open ports and run a focused -sC -sV against just those.",
        tags: ["nmap", "full-port", "p-"],
      },
      {
        id: "scan-focused",
        command: "nmap -p22,80,445,8080 -sC -sV -oA nmap_focused <TARGET>",
        platform: "any",
        purpose: "Deep version+script scan on the specific open ports.",
        why: "Now that you know which ports are open, spend the detailed scan only on them — faster and cleaner.",
        lookFor: ["Exact versions", "NSE script findings"],
        risk: "low",
        next: "Enumerate each service in priority order.",
        tags: ["nmap", "focused", "sV"],
      },
      {
        id: "scan-udp",
        command: "nmap -sU --top-ports 50 -oA nmap_udp <TARGET>",
        platform: "any",
        purpose: "Scan the most common UDP ports.",
        whenToUse: "When TCP looks sparse or you suspect SNMP/DNS/TFTP.",
        why: "UDP services (SNMP 161, DNS 53, TFTP 69) are easy to overlook and sometimes hold the key.",
        flags: [{ flag: "-sU", meaning: "UDP scan (slower — limit the port count)" }],
        lookFor: ["SNMP (161)", "DNS (53)", "Other UDP services"],
        risk: "low",
        next: "Enumerate any interesting UDP service (e.g. SNMP community strings).",
        tags: ["nmap", "udp", "snmp"],
      },
    ],
    lookFor: ["High-port services the default scan missed", "UDP services"],
    commonMistakes: ["Only ever running the default scan", "Ignoring UDP entirely"],
    next: ["scan-interpreting"],
    keywords: ["nmap", "full port", "p-", "udp", "min-rate"],
  },
  {
    id: "scan-interpreting",
    title: "Reading a Scan and Deciding What's Next",
    category: "scanning",
    categoryLabel: "Scanning",
    difficulty: "beginner",
    summary: "Convert a raw port list into a prioritized plan using the port→service→workflow mapping.",
    estMinutes: 6,
    objectives: ["Prioritize services", "Recognize OS and role signatures", "Translate results into a concrete next step"],
    teacherIntro:
      "A scan result is not a conclusion — it's a to-do list. The skill is turning 'these ports are open' into 'here's what I'll check first and why'. Let's practice reading, not just running.",
    why: "Prioritization saves time. Two testers with the same scan get different results based on how well they read it and where they choose to look first.",
    notes: [
      { heading: "Prioritize by information yield", body: "Web (80/443) and SMB (445) usually reveal the most, fastest. Databases and remote-access services (SSH/RDP/WinRM) matter more once you have credentials." },
      { heading: "Read the whole result", body: "Version strings, script output, page titles, and OS guesses are all clues. The 'boring' SSH banner tells you the distro; the HTTP title might name the app." },
      { heading: "Note, don't chase everything", body: "Record every open port. Investigate the highest-yield one first, but keep the rest on your list — you'll return.", tone: "teacher" },
    ],
    lookFor: ["Highest-yield service to start with", "OS/role signatures (DC, Linux web host)", "Non-standard ports worth a closer look"],
    branches: [
      { condition: "80/443 present", outcome: "Web first.", goto: { type: "service", id: "http" } },
      { condition: "445 + domain name", outcome: "SMB, then AD.", goto: { type: "service", id: "smb" } },
      { condition: "Only remote-access ports (22/3389/5985)", outcome: "You likely need credentials first — go find them elsewhere or via full-port scan.", goto: { type: "lesson", id: "creds-reuse" } },
    ],
    next: ["svc-http", "svc-smb"],
    keywords: ["interpret", "scan", "prioritize", "next step"],
  },
];
