import type { Lesson } from "@/types";

export const webLessons: Lesson[] = [
  {
    id: "web-methodology",
    title: "Web Enumeration Methodology",
    category: "web",
    categoryLabel: "Web Security",
    difficulty: "beginner",
    summary: "The order to understand a web app: server → tech → headers → source → files → directories → JS → APIs → auth.",
    estMinutes: 10,
    methodology: ["OWASP WSTG", "PTES"],
    objectives: ["Fingerprint the stack", "Map the application structure", "Find auth and API surfaces before testing bugs"],
    teacherIntro:
      "We found HTTP. Before touching any vulnerability, we need to understand the application: what it's built with, how it's structured, and where the interesting functionality lives. Understanding first, testing second.",
    why: "Blindly firing scanners at a web app produces noise and false positives. A methodical map tells you which tests actually make sense here.",
    notes: [
      { heading: "The order", body: "1) Identify the server/framework. 2) Read headers and cookies. 3) View page source and linked JavaScript. 4) robots.txt / sitemap.xml. 5) Content discovery (dirs/files). 6) Enumerate APIs and parameters. 7) Map authentication and authorization. Only then start vulnerability testing." },
      { heading: "JavaScript is a map", body: "Modern apps put endpoints, parameter names, and even secrets in their JS bundles. Read them — they often reveal the API you're supposed to attack.", tone: "tip" },
      { heading: "Don't tool-spam", body: "Each tool should answer a question you actually have. 'What tech is this?' → whatweb. 'What paths exist?' → ffuf. Not 'run everything and hope'.", tone: "teacher" },
    ],
    commands: [
      { id: "web-curl-src", command: "curl -s http://<TARGET>/ | grep -Eio 'src=\"[^\"]+\"|href=\"[^\"]+\"'", platform: "any", purpose: "Extract linked scripts and resources from the homepage.", why: "The linked JS/CSS often reveals the app framework and API paths.", lookFor: ["/api/ paths", "JS bundle names", "hidden endpoints"], risk: "low", tags: ["web", "curl", "source"] },
      { id: "web-whatweb2", command: "whatweb -a 3 http://<TARGET>", platform: "any", purpose: "Fingerprint technologies aggressively.", why: "Confirms CMS/framework/versions to focus your testing.", lookFor: ["CMS + version", "server-side language"], risk: "low", tags: ["web", "whatweb"] },
    ],
    lookFor: ["Server + framework", "Cookies and security headers", "API endpoints in JS", "Login/admin areas"],
    branches: [
      { condition: "You found a login page", outcome: "Map authentication next.", goto: { type: "lesson", id: "web-authentication" } },
      { condition: "You found content to discover", outcome: "Run content discovery.", goto: { type: "lesson", id: "web-content-discovery" } },
    ],
    next: ["web-content-discovery", "web-authentication", "web-burp"],
    related: ["svc-http"],
    keywords: ["web", "methodology", "whatweb", "enumeration", "http"],
  },
  {
    id: "web-content-discovery",
    title: "Content Discovery",
    category: "web",
    categoryLabel: "Web Security",
    difficulty: "beginner",
    summary: "Find unlinked directories and files with ffuf/feroxbuster, choose the right wordlist, and interpret status codes.",
    estMinutes: 9,
    methodology: ["OWASP WSTG-CONF"],
    objectives: ["Run directory and file discovery", "Pick wordlists and extensions", "Interpret 200/301/403 correctly"],
    teacherIntro:
      "Applications hide functionality behind paths nothing links to. Content discovery brute forces likely names to reveal the real structure — admin panels, backups, source control, and dev endpoints.",
    why: "The homepage is marketing; the interesting stuff is usually unlinked. Discovery is often the step that turns 'a website' into 'a way in'.",
    commands: [
      {
        id: "web-ffuf-dir2",
        command: "ffuf -u http://<TARGET>/FUZZ -w /usr/share/seclists/Discovery/Web-Content/directory-list-2.3-medium.txt -mc all -fc 404 -t 40",
        platform: "kali",
        purpose: "Discover directories and files.",
        why: "Reveals the app's real structure. Matching all codes and filtering 404 surfaces 403s and redirects that confirm something exists.",
        flags: [
          { flag: "-mc all", meaning: "Consider all status codes" },
          { flag: "-fc 404", meaning: "Filter out 404s (not found)" },
          { flag: "-e .php,.txt,.bak", meaning: "Append extensions matching the stack" },
        ],
        exampleOutput: "admin [301]\n.git/ [301]\nbackup.zip [200]\nlogin.php [200]\nconfig.php.bak [200]",
        lookFor: [".git / .svn", "*.bak / *.zip / *.old", "admin / dev / api", "403s worth revisiting with auth"],
        commonMistakes: ["Tiny wordlist", "Not appending stack-specific extensions", "Ignoring 403s"],
        risk: "medium",
        next: ".git exposed? Dump it. Backup file? Download and read it.",
        tags: ["web", "ffuf", "feroxbuster", "gobuster", "discovery"],
      },
      { id: "web-gitdump", command: "git-dumper http://<TARGET>/.git/ ./loot", platform: "kali", purpose: "Reconstruct source from an exposed .git directory.", why: "Source code often contains credentials, hidden endpoints, and the exact logic you're attacking.", lookFor: ["config with DB creds", "API keys", "commented-out endpoints"], risk: "medium", tags: ["web", "git", "source-leak"] },
    ],
    lookFor: ["Exposed source (.git)", "Backup/config files", "Admin and API paths"],
    branches: [
      { condition: "You dumped source containing credentials", outcome: "Record the creds and test reuse across services.", goto: { type: "lesson", id: "creds-reuse" } },
      { condition: "You found an admin login", outcome: "Analyze the authentication mechanism.", goto: { type: "lesson", id: "web-authentication" } },
    ],
    exercise: {
      id: "wcd-ex",
      prompt: "Discovery returns '/.git/ [301]'. What's the highest-value next move?",
      options: ["Ignore it — 301 is just a redirect", "Dump the repository to read the source", "Brute force the login page", "Run a full port scan again"],
      answerIndex: 1,
      explanation: "An exposed /.git/ almost always means you can reconstruct the application's source code with git-dumper. Source frequently contains credentials, secret endpoints, and the exact logic you're testing — one of the best outcomes in web discovery.",
    },
    next: ["web-authentication", "web-authorization"],
    keywords: ["content discovery", "ffuf", "gobuster", "feroxbuster", "directory", "git"],
  },
  {
    id: "web-authentication",
    title: "Testing Authentication",
    category: "web",
    categoryLabel: "Web Security",
    difficulty: "intermediate",
    summary: "Default creds, username enumeration, weak lockout, and how to reason about a login before attacking it.",
    estMinutes: 9,
    methodology: ["OWASP WSTG-ATHN"],
    objectives: ["Identify the auth mechanism", "Check default creds and user enumeration", "Reason about lockout and rate limits"],
    teacherIntro:
      "A login page is a question: who are the valid users, and how strong is the gate? Before brute forcing anything, we look for default credentials, username enumeration, and whether the app even limits attempts.",
    why: "Most 'password attacks' succeed because of defaults, reuse, or weak lockout — not raw cracking. Reasoning first avoids noise and lockouts.",
    notes: [
      { heading: "Username enumeration", body: "Different responses for valid vs invalid usernames ('user not found' vs 'wrong password', or timing differences) let you build a user list before touching passwords." },
      { heading: "Default & reused creds", body: "Try documented defaults for the identified product first. Then try any credentials you found elsewhere — reuse is rampant.", tone: "tip" },
      { heading: "Respect lockout", body: "Check the lockout policy before spraying. Locking out real accounts is disruptive and, in a real engagement, a serious problem.", tone: "warning" },
    ],
    commands: [
      { id: "web-hydra-form", command: "hydra -L users.txt -P passwords.txt <TARGET> http-post-form \"/login:user=^USER^&pass=^PASS^:Invalid\"", platform: "kali", purpose: "Test credentials against a login form (authorized labs).", why: "Automates credential testing once you understand the form and the failure indicator.", flags: [{ flag: "-L/-P", meaning: "Username/password lists" }, { flag: ":Invalid", meaning: "String that marks a failed login" }], risk: "high", commonMistakes: ["Wrong failure string → all attempts look 'successful'", "Ignoring lockout"], next: "A valid login → map what the account can access (authorization).", tags: ["web", "hydra", "auth", "brute"] },
    ],
    lookFor: ["Default credentials", "Username enumeration signal", "Missing rate-limit/lockout", "Verbose error messages"],
    branches: [
      { condition: "You authenticated", outcome: "Now test authorization — can you reach things this account shouldn't?", goto: { type: "lesson", id: "web-authorization" }, risk: "medium" },
    ],
    commonMistakes: ["Brute forcing before checking defaults/reuse", "Ignoring the lockout policy"],
    next: ["web-authorization"],
    keywords: ["authentication", "login", "hydra", "default credentials", "brute force"],
  },
  {
    id: "web-authorization",
    title: "Testing Authorization (IDOR / BOLA)",
    category: "web",
    categoryLabel: "Web Security",
    difficulty: "intermediate",
    summary: "Once you're in as one user, test whether you can reach data or actions belonging to others.",
    estMinutes: 8,
    methodology: ["OWASP WSTG-ATHZ", "OWASP API Top 10: BOLA"],
    objectives: ["Distinguish authentication from authorization", "Test object-level access (IDOR/BOLA)", "Test function-level access"],
    teacherIntro:
      "Authentication is 'who are you'; authorization is 'what are you allowed to do'. A huge class of real bugs is authorization failure: you're logged in as a low-priv user, but the app doesn't stop you from reading or changing someone else's data.",
    why: "IDOR/BOLA are among the most common and impactful web findings, and they need no exotic payloads — just careful, methodical testing of access control.",
    notes: [
      { heading: "IDOR / BOLA", body: "Change an identifier (?id=123 → 124, /api/users/5 → /6). If you get another user's data, that's a broken object-level authorization finding." },
      { heading: "Function-level access", body: "Try to reach admin-only endpoints as a normal user. Sometimes the UI hides the button but the endpoint is unprotected." },
      { heading: "Two accounts help", body: "If you can register two accounts, use one to reference the other's objects — the cleanest way to prove impact.", tone: "tip" },
    ],
    lookFor: ["Predictable IDs in URLs/APIs", "Admin endpoints reachable without admin", "Missing ownership checks"],
    branches: [
      { condition: "You accessed another user's data", outcome: "That's a validated authorization finding — capture evidence and record impact.", goto: { type: "phase", id: "impact" }, risk: "high" },
    ],
    exercise: {
      id: "waz-ex",
      prompt: "Logged in as a normal user, you change /api/invoices/1043 to /api/invoices/1042 and receive another company's invoice. What is this?",
      options: ["Cross-site scripting (XSS)", "SQL injection", "Broken object-level authorization (IDOR/BOLA)", "A false positive — ignore it"],
      answerIndex: 2,
      explanation: "Accessing another user's object by manipulating its identifier is classic IDOR / BOLA — a broken authorization control. It needs no special payload and is often high impact. Capture the request/response as evidence.",
    },
    next: ["web-burp"],
    keywords: ["authorization", "idor", "bola", "access control", "api"],
  },
  {
    id: "web-burp",
    title: "The Burp Suite Workflow",
    category: "web",
    categoryLabel: "Web Security",
    difficulty: "intermediate",
    summary: "Proxy → HTTP history → Repeater → modify → compare → hypothesis → validate. The loop for manual web testing.",
    estMinutes: 8,
    methodology: ["OWASP WSTG"],
    objectives: ["Route traffic through Burp", "Use Repeater to test one request repeatedly", "Form and validate hypotheses"],
    teacherIntro:
      "Automated tools find the obvious; Burp is how you test ideas. The core loop: capture a request, send it to Repeater, change one thing, observe the difference, and use that to form and test a hypothesis.",
    why: "Real web bugs are found by understanding a single request deeply and manipulating it deliberately — exactly what Repeater is for.",
    notes: [
      { heading: "The tools", body: "Proxy captures traffic. HTTP history is your record. Repeater re-sends a single request with edits. Intruder automates parameter fuzzing. Comparer/Decoder help analyze responses and encodings." },
      { heading: "Change one thing", body: "In Repeater, alter a single parameter and compare responses. Disciplined one-variable changes make cause and effect obvious." },
      { heading: "Hypothesis loop", body: "Observe → hypothesize ('maybe id is not authorization-checked') → test the smallest change → confirm or discard. Record what you learn.", tone: "teacher" },
    ],
    lookFor: ["Parameters worth manipulating", "Differences in response to small changes", "Reflected input or error leakage"],
    next: ["web-authorization", "web-sqli"],
    keywords: ["burp", "repeater", "proxy", "intruder", "web testing"],
  },
];
