import type { ServiceModule } from "@/types";

export const mysqlModule: ServiceModule = {
  id: "mysql",
  name: "MySQL / MariaDB",
  ports: [3306],
  category: "database",
  tagline: "Weak or blank root, remote access, and readable data.",
  what: "A relational database. Misconfigurations include remote root access, blank/weak passwords, and (privilege-dependent) file read/write.",
  why: "Databases store the crown jewels: credentials, hashes, and application data. Access here often yields creds that unlock other services.",
  objective: "Authenticate (try weak/blank creds), enumerate databases and users, and read interesting tables.",
  risk: "medium",
  commands: [
    {
      id: "mysql-connect",
      command: "mysql -h <TARGET> -u root -p",
      platform: "any",
      purpose: "Connect to MySQL as root.",
      why: "Remote root with a blank or weak password is a classic quick win.",
      lookFor: ["Successful login", "Version banner"],
      commonMistakes: ["Not trying an empty password", "Assuming remote access is disabled without testing"],
      risk: "medium",
      next: "Enumerate databases: SHOW DATABASES;",
      tags: ["mysql", "3306", "root"],
    },
    {
      id: "mysql-enum",
      command: "SHOW DATABASES; SELECT user,authentication_string FROM mysql.user;",
      platform: "any",
      purpose: "List databases and dump stored credential hashes.",
      why: "Application databases and the mysql.user table both commonly contain crackable credentials.",
      lookFor: ["Application DBs", "Password hashes to crack offline", "Cleartext creds in app tables"],
      risk: "medium",
      next: "Crack hashes; reuse creds elsewhere.",
      tags: ["mysql", "enumeration", "hashes"],
    },
  ],
  lookFor: ["Blank/weak root", "Remote access enabled", "Credential hashes", "App data with secrets"],
  branches: [
    {
      condition: "You dumped password hashes",
      outcome: "Identify the hash type and crack offline; test reuse.",
      goto: { type: "lesson", id: "creds-hashes" },
      risk: "medium",
    },
  ],
  relatedLessons: ["svc-mysql", "creds-hashes"],
  keywords: ["mysql", "mariadb", "3306", "database", "sql"],
};

export const mssqlModule: ServiceModule = {
  id: "mssql",
  name: "Microsoft SQL Server",
  ports: [1433],
  category: "database",
  tagline: "xp_cmdshell, impersonation, and linked servers.",
  what: "Microsoft's relational database, tightly integrated with Windows auth. Beyond data, it offers well-known routes to command execution.",
  why: "With sufficient privileges, MSSQL can execute OS commands via xp_cmdshell, impersonate other logins, or pivot through linked servers — a direct path from data access to host access.",
  objective: "Authenticate (SQL or Windows auth), enumerate privileges, and assess command-execution paths within scope.",
  risk: "high",
  commands: [
    {
      id: "mssql-connect",
      command: "impacket-mssqlclient <USER>@<TARGET> -windows-auth",
      platform: "kali",
      purpose: "Connect to MSSQL with Windows or SQL authentication.",
      why: "A working session lets you enumerate roles and test whether command execution is reachable.",
      flags: [{ flag: "-windows-auth", meaning: "Use Windows (NTLM) auth instead of SQL auth" }],
      lookFor: ["Login succeeds", "Whether you are sysadmin", "Available databases"],
      risk: "medium",
      next: "Check privileges; test impersonation/xp_cmdshell (authorized only).",
      tags: ["mssql", "1433", "impacket"],
    },
    {
      id: "mssql-xpcmd",
      command: "EXEC xp_cmdshell 'whoami';",
      platform: "windows",
      purpose: "Attempt OS command execution via xp_cmdshell.",
      whenToUse: "Only with sysadmin (or via impersonation), and only within an authorized engagement.",
      why: "If enabled, this runs OS commands as the SQL service account — often a direct route to a shell.",
      lookFor: ["Command output = execution works", "The service account context"],
      commonMistakes: ["Assuming it's disabled — it can be enabled if you're sysadmin", "Running destructive commands"],
      risk: "critical",
      next: "Leverage execution to a controlled shell; document impact conservatively.",
      tags: ["mssql", "xp_cmdshell", "rce"],
    },
  ],
  lookFor: ["sysadmin membership", "Impersonatable logins", "Linked servers", "xp_cmdshell availability"],
  branches: [
    {
      condition: "You have sysadmin or command execution",
      outcome: "This is code execution on the host — proceed to initial access carefully and record impact.",
      goto: { type: "phase", id: "initial_access" },
      risk: "critical",
    },
  ],
  commonMistakes: ["Treating MSSQL as data-only and missing the command-execution paths"],
  relatedLessons: ["svc-mssql"],
  keywords: ["mssql", "1433", "sqlserver", "xp_cmdshell", "impacket", "sa"],
};
