import type { ServiceModule } from "@/types";

export const httpModule: ServiceModule = {
  id: "http",
  name: "HTTP / HTTPS",
  ports: [80, 443, 8080, 8000, 8443],
  category: "web",
  tagline: "The richest attack surface on most targets.",
  what: "A web server exposes an application: pages, endpoints, logins, APIs, and files. Web applications usually give up a large amount of information quickly, which is why we often start here.",
  why: "Web apps are complex and human-written, so they accumulate bugs: exposed files, weak authentication, injectable parameters, and logic flaws. Even before any vulnerability, the app tells you what the target does.",
  objective:
    "Identify the server and technology, map the application structure, find authentication and API surfaces, and locate interesting files — before testing any single vulnerability.",
  risk: "low",
  commands: [
    {
      id: "http-headers",
      command: "curl -sSIk https://<TARGET>",
      platform: "any",
      purpose: "Fetch only the HTTP response headers.",
      why: "Headers reveal the server (Apache/nginx/IIS), framework hints, redirects, cookies, and security headers — without downloading the whole page.",
      flags: [
        { flag: "-I", meaning: "HEAD request: headers only" },
        { flag: "-k", meaning: "Ignore TLS certificate errors (labs use self-signed certs)" },
        { flag: "-s", meaning: "Silent (no progress meter)" },
      ],
      exampleOutput:
        "HTTP/1.1 200 OK\nServer: Apache/2.4.41 (Ubuntu)\nX-Powered-By: PHP/7.4.3\nSet-Cookie: PHPSESSID=...; path=/",
      lookFor: ["Server + version", "X-Powered-By / framework", "Set-Cookie names", "Redirect Location", "Missing security headers"],
      risk: "low",
      next: "Fingerprint the technology stack with whatweb.",
      tags: ["http", "curl", "headers"],
    },
    {
      id: "http-whatweb",
      command: "whatweb -a 3 http://<TARGET>",
      platform: "any",
      purpose: "Fingerprint web technologies (CMS, frameworks, libraries).",
      why: "Knowing it's WordPress vs a custom PHP app vs Tomcat completely changes which enumeration and known-issue checks make sense.",
      flags: [{ flag: "-a 3", meaning: "Aggression level 3 (more requests, more detail)" }],
      exampleOutput:
        "http://10.10.10.10 [200 OK] Apache[2.4.41], Country[RESERVED], HTTPServer[Ubuntu Linux][Apache/2.4.41], PHP[7.4.3], WordPress[5.7]",
      lookFor: ["CMS name + version", "JS frameworks", "Server-side language", "Interesting plugins"],
      risk: "low",
      next: "Read robots.txt / sitemap and the raw page source for hints.",
      tags: ["http", "whatweb", "fingerprint"],
    },
    {
      id: "http-robots",
      command: "curl -s http://<TARGET>/robots.txt",
      platform: "any",
      purpose: "Read robots.txt for disallowed (often interesting) paths.",
      why: "Admins list paths they don't want indexed — which frequently points straight at admin panels, backups, or dev areas.",
      exampleOutput: "User-agent: *\nDisallow: /admin/\nDisallow: /backup/\nDisallow: /dev/",
      lookFor: ["/admin", "/backup", "/dev", "/api", "unusual paths"],
      risk: "low",
      next: "Note interesting paths, then run content discovery.",
      tags: ["http", "robots"],
    },
    {
      id: "http-ffuf-dir",
      command:
        "ffuf -u http://<TARGET>/FUZZ -w /usr/share/seclists/Discovery/Web-Content/directory-list-2.3-medium.txt -mc 200,204,301,302,307,401,403 -t 40",
      platform: "any",
      purpose: "Content discovery: find directories and files not linked anywhere.",
      whenToUse: "After you know the tech stack, to reveal hidden application structure.",
      why: "Applications hide functionality behind unlinked paths. Discovery maps the real attack surface, not just what's on the front page.",
      flags: [
        { flag: "-u ...FUZZ", meaning: "FUZZ marks where wordlist entries are inserted" },
        { flag: "-w", meaning: "Wordlist (SecLists is a great default)" },
        { flag: "-mc", meaning: "Match these HTTP status codes" },
        { flag: "-t 40", meaning: "40 concurrent threads (tune to avoid overwhelming the target)" },
        { flag: "-e .php,.txt,.bak", meaning: "Append extensions to each word (add when you know the language)" },
      ],
      exampleOutput:
        "admin                   [Status: 301, Size: 312]\nlogin.php               [Status: 200, Size: 1543]\nbackup                  [Status: 403, Size: 277]\n.git                    [Status: 301, Size: 310]",
      lookFor: ["login/admin panels", ".git / .svn (source leak)", "backup / .bak files", "api / dev endpoints", "403s worth revisiting"],
      commonMistakes: [
        "Using a tiny wordlist and concluding 'nothing here'",
        "Ignoring 403s — they confirm something exists",
        "Not appending extensions matching the stack (.php, .aspx, .jsp)",
      ],
      risk: "medium",
      next: "For each interesting path, investigate what it does. .git → dump the repo.",
      tags: ["http", "ffuf", "content-discovery", "gobuster", "feroxbuster"],
    },
    {
      id: "http-vhost",
      command:
        "ffuf -u http://<TARGET>/ -H 'Host: FUZZ.<DOMAIN>' -w /usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt -fs <BASELINE_SIZE>",
      platform: "any",
      purpose: "Virtual host discovery via the Host header.",
      whenToUse: "When the target serves different sites based on hostname (common on HTB).",
      why: "A single IP can host many vhosts. The default page may be boring while a named vhost hides the real app.",
      flags: [{ flag: "-fs", meaning: "Filter out the baseline response size (the default vhost)" }],
      lookFor: ["Response sizes/status that differ from baseline"],
      risk: "low",
      next: "Add discovered vhosts to /etc/hosts and enumerate each.",
      tags: ["http", "vhost", "ffuf"],
    },
  ],
  lookFor: [
    "Server and framework versions",
    "Login / admin panels",
    "Exposed source control (.git)",
    "Backup and config files",
    "API endpoints and parameters",
    "Verbose error messages",
  ],
  branches: [
    {
      condition: "You found a login page",
      outcome: "Map the auth mechanism: default creds, user enumeration, and whether it's the app's real entry point.",
      goto: { type: "lesson", id: "web-authentication" },
    },
    {
      condition: "You found /.git exposed",
      outcome: "Dump the repository — source code often contains credentials, endpoints, and logic you can read directly.",
      goto: { type: "lesson", id: "web-content-discovery" },
      risk: "medium",
    },
    {
      condition: "You found an API endpoint",
      outcome: "Enumerate methods and parameters; look for IDOR/BOLA and missing authorization.",
      goto: { type: "lesson", id: "web-authorization" },
    },
    {
      condition: "Input reflected or errors leak SQL",
      outcome: "Move to the relevant web vulnerability module and validate safely before claiming anything.",
      goto: { type: "lesson", id: "web-sqli" },
      risk: "high",
    },
  ],
  commonMistakes: [
    "Firing every tool at once instead of understanding the app first",
    "Treating a scanner alert as a confirmed vulnerability",
    "Skipping page source and JavaScript, which often reveal endpoints",
  ],
  relatedLessons: ["svc-http", "web-methodology", "web-content-discovery", "web-authentication"],
  keywords: ["http", "https", "web", "curl", "ffuf", "gobuster", "whatweb", "80", "443"],
};
