import type { ServiceModule } from "@/types";

export const sshModule: ServiceModule = {
  id: "ssh",
  name: "SSH",
  ports: [22],
  category: "remote",
  tagline: "Encrypted remote administration — usually not the way in by itself.",
  what: "Secure Shell provides encrypted remote command-line access. The banner reveals the implementation and version; authentication may be by password or key.",
  why: "SSH is rarely the initial foothold on its own — it's hardened and brute forcing is noisy and slow. It becomes valuable when you find credentials or a private key elsewhere and reuse them here.",
  objective: "Read the version/banner, understand the accepted auth methods, and be ready to reuse any credentials or keys you discover.",
  risk: "low",
  commands: [
    {
      id: "ssh-banner",
      command: "nc <TARGET> 22",
      platform: "any",
      purpose: "Read the SSH banner/version.",
      why: "The version (e.g. OpenSSH 8.2p1 Ubuntu) hints at the OS/distro and rules certain issues in or out.",
      exampleOutput: "SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.5",
      lookFor: ["OpenSSH version", "Distro hint (Ubuntu/Debian)", "Non-standard implementations"],
      risk: "low",
      next: "Note the OS hint; check auth methods.",
      tags: ["ssh", "banner", "nc"],
    },
    {
      id: "ssh-authmethods",
      command: "ssh -v <USER>@<TARGET>",
      platform: "any",
      purpose: "Observe which authentication methods the server offers.",
      why: "If only publickey is accepted, password guessing is pointless — you need a key. If password is accepted, discovered creds may work.",
      flags: [{ flag: "-v", meaning: "Verbose — prints auth negotiation" }],
      lookFor: ["'Authentications that can continue: publickey,password'", "Key-only vs password"],
      commonMistakes: ["Brute forcing when only key auth is allowed"],
      risk: "low",
      next: "If you have a key: chmod 600 and connect with -i.",
      tags: ["ssh", "auth"],
    },
    {
      id: "ssh-key",
      command: "chmod 600 id_rsa && ssh -i id_rsa <USER>@<TARGET>",
      platform: "any",
      purpose: "Authenticate with a discovered private key.",
      whenToUse: "After finding a private key in a share, web directory, or backup.",
      why: "Keys found elsewhere are a common, quiet path to a foothold — no brute force required.",
      lookFor: ["Successful shell", "Which user the key belongs to"],
      commonMistakes: ["Forgetting chmod 600 (SSH refuses world-readable keys)"],
      risk: "medium",
      next: "You have a shell — stabilize it and identify the OS.",
      tags: ["ssh", "key", "id_rsa"],
    },
  ],
  lookFor: ["OpenSSH version + distro hint", "Accepted auth methods", "Whether discovered creds/keys work here"],
  branches: [
    {
      condition: "You obtained a shell via SSH",
      outcome: "Stop and enumerate: current user, privileges, and OS before anything else.",
      goto: { type: "phase", id: "initial_access" },
      risk: "medium",
    },
    {
      condition: "Only public-key auth is allowed",
      outcome: "Go find a key — search other services, shares, and web directories. Don't brute force.",
      goto: { type: "lesson", id: "creds-reuse" },
    },
  ],
  commonMistakes: ["Brute forcing SSH as a first move (noisy, slow, often futile)"],
  relatedLessons: ["svc-ssh", "creds-reuse"],
  keywords: ["ssh", "22", "openssh", "key", "id_rsa"],
};

export const ftpModule: ServiceModule = {
  id: "ftp",
  name: "FTP",
  ports: [21],
  category: "network",
  tagline: "Old, chatty, and often anonymously accessible.",
  what: "File Transfer Protocol moves files, frequently in cleartext. Many deployments allow anonymous login or expose a revealing version banner.",
  why: "Anonymous FTP can hand you files directly — sometimes source code, configs, or credentials. If you can also write, and the files are served by a web server, that can become code execution.",
  objective: "Check for anonymous access, read the banner/version, and inspect any accessible files (including whether uploads land in a web-served path).",
  risk: "low",
  commands: [
    {
      id: "ftp-anon",
      command: "ftp <TARGET>",
      platform: "any",
      purpose: "Attempt an interactive FTP login (try user 'anonymous').",
      why: "Anonymous access is the fastest possible win here and requires nothing but a username.",
      exampleOutput: "220 (vsFTPd 3.0.3)\nName (10.10.10.10): anonymous\n230 Login successful.\nftp> ls",
      lookFor: ["'230 Login successful' with anonymous", "vsFTPd/ProFTPD version", "Readable/writable directories"],
      risk: "low",
      next: "List and download everything; check for writable dirs.",
      tags: ["ftp", "anonymous", "21"],
    },
    {
      id: "ftp-wget-mirror",
      command: "wget -r ftp://anonymous:anonymous@<TARGET>/",
      platform: "any",
      purpose: "Recursively download everything readable over FTP.",
      why: "Pull the whole tree locally so you can grep it for secrets at your leisure.",
      flags: [{ flag: "-r", meaning: "Recursive mirror" }],
      lookFor: ["config files", "backups", "source code", "credentials in files"],
      risk: "low",
      next: "grep the download for 'password', keys, and connection strings.",
      tags: ["ftp", "wget", "download"],
    },
    {
      id: "ftp-nmap",
      command: "nmap -p21 -sV -sC <TARGET>",
      platform: "any",
      purpose: "Version detection plus default FTP NSE scripts.",
      why: "NSE checks anonymous access and known FTP issues automatically.",
      lookFor: ["ftp-anon result", "Exact daemon version"],
      risk: "low",
      next: "If anonymous works, browse; otherwise reuse creds found elsewhere.",
      tags: ["ftp", "nmap", "nse"],
    },
  ],
  lookFor: ["Anonymous login allowed", "Writable directories", "Files served elsewhere (web)", "Daemon version"],
  branches: [
    {
      condition: "Anonymous login works and you can write",
      outcome: "If uploads are served by a web server, you may be able to upload a web shell. Validate the path first.",
      goto: { type: "service", id: "http" },
      risk: "high",
    },
    {
      condition: "You found credentials in downloaded files",
      outcome: "Record them and test reuse on SSH/SMB/web.",
      goto: { type: "lesson", id: "creds-reuse" },
    },
  ],
  commonMistakes: ["Not checking whether FTP-uploaded files are reachable via HTTP", "Ignoring the version banner"],
  relatedLessons: ["svc-ftp", "creds-reuse"],
  keywords: ["ftp", "21", "anonymous", "vsftpd", "proftpd"],
};

export const dnsModule: ServiceModule = {
  id: "dns",
  name: "DNS",
  ports: [53],
  category: "network",
  tagline: "Names map the network — and sometimes hand you the whole zone.",
  what: "The Domain Name System resolves names to addresses. A misconfigured server may allow a zone transfer (AXFR), dumping every record it holds.",
  why: "A successful zone transfer reveals hostnames, subdomains, mail servers, and internal structure in one request. In Active Directory, DNS usually runs on the Domain Controller.",
  objective: "Attempt a zone transfer, enumerate records, and turn discovered hostnames into new targets.",
  risk: "low",
  commands: [
    {
      id: "dns-axfr",
      command: "dig axfr @<TARGET> <DOMAIN>",
      platform: "any",
      purpose: "Attempt a full DNS zone transfer.",
      why: "If allowed, AXFR returns the entire zone — the single fastest way to enumerate a domain's hosts.",
      exampleOutput:
        "<DOMAIN>.            604800  IN  SOA  ns1.<DOMAIN>. ...\nwww                 IN  A    10.10.10.10\ndev                 IN  A    10.10.10.20\nmail                IN  A    10.10.10.30",
      lookFor: ["Multiple A records (new hosts)", "dev/staging/internal names", "Mail and NS records"],
      commonMistakes: ["Forgetting the @ before the server", "Not trying each NS listed for the zone"],
      risk: "low",
      next: "Add discovered names to /etc/hosts and enumerate each host.",
      tags: ["dns", "axfr", "dig", "zone-transfer"],
    },
    {
      id: "dns-nslookup",
      command: "nslookup -type=any <DOMAIN> <TARGET>",
      platform: "any",
      purpose: "Query records for a domain against a specific server.",
      why: "Even without AXFR, individual record queries reveal mail servers, name servers, and TXT records.",
      lookFor: ["MX, NS, TXT records", "SPF/verification TXT records"],
      risk: "low",
      next: "Use discovered names to expand scope (within authorization).",
      tags: ["dns", "nslookup"],
    },
    {
      id: "dns-brute",
      command: "dnsenum --enum <DOMAIN>",
      platform: "kali",
      purpose: "Enumerate DNS including subdomain brute forcing.",
      why: "When AXFR is refused, brute forcing common subdomains still surfaces hosts.",
      lookFor: ["Resolvable subdomains", "Wildcard behavior (false positives)"],
      risk: "low",
      next: "Confirm live hosts and enumerate their services.",
      tags: ["dns", "dnsenum", "subdomains"],
    },
  ],
  lookFor: ["AXFR allowed", "New hostnames/subdomains", "Mail/NS records", "AD DC indicators (53 with 88/389)"],
  branches: [
    {
      condition: "Zone transfer succeeded",
      outcome: "Each new hostname is a new target — record them and scan the interesting ones.",
      goto: { type: "phase", id: "scanning" },
    },
    {
      condition: "53 appears with 88/389/445",
      outcome: "This is almost certainly an AD Domain Controller — switch to the Active Directory workflow.",
      goto: { type: "lesson", id: "ad-domain" },
    },
  ],
  commonMistakes: ["Only querying one name server", "Not adding discovered vhosts to /etc/hosts before web enumeration"],
  relatedLessons: ["svc-dns", "recon-dns", "ad-domain"],
  keywords: ["dns", "53", "axfr", "zone transfer", "dig", "subdomain"],
};
