import type { ServiceModule } from "@/types";

export const smbModule: ServiceModule = {
  id: "smb",
  name: "SMB",
  ports: [139, 445],
  category: "network",
  tagline: "File shares — and in Active Directory, a primary enumeration surface.",
  what: "Server Message Block shares files and printers and carries a lot of Windows/AD metadata. On domain hosts it also exposes users, groups, and password policy.",
  why: "SMB frequently allows anonymous or guest access to shares that contain credentials, scripts, or sensitive files. Even without a login it leaks the OS, domain name, and signing status — all of which shape the AD attack path.",
  objective:
    "Determine what SMB exposes: shares, null/guest access, OS and domain info, signing status, and (with creds) users and admin access.",
  risk: "low",
  commands: [
    {
      id: "smb-nxc-info",
      command: "nxc smb <TARGET>",
      platform: "kali",
      purpose: "Grab host banner: OS, hostname, domain, and SMB signing status.",
      why: "This one line tells you if the host is domain-joined, its exact name, and whether SMB signing is required (relevant to relay attacks).",
      flags: [{ flag: "(no creds)", meaning: "Just connecting reveals the banner" }],
      exampleOutput:
        "SMB   10.10.10.10  445  DC01  [*] Windows 10 / Server 2019 Build 17763 x64 (name:DC01) (domain:corp.local) (signing:True) (SMBv1:False)",
      lookFor: ["OS + build", "Hostname", "Domain name (corp.local)", "signing:True/False", "SMBv1 enabled?"],
      risk: "low",
      next: "Try a null/guest session to list shares.",
      tags: ["smb", "netexec", "nxc", "crackmapexec"],
    },
    {
      id: "smb-shares-null",
      command: "nxc smb <TARGET> -u '' -p '' --shares",
      platform: "kali",
      purpose: "List shares using a null session (no credentials).",
      why: "Anonymous share access is a common quick win — READ on a share can leak credentials or hints; WRITE can enable payload delivery.",
      exampleOutput:
        "SHARE           PERMISSIONS   REMARK\n-----           -----------   ------\nADMIN$                        Remote Admin\nC$                            Default share\nIPC$            READ          Remote IPC\nbackups         READ          \nprofiles        READ,WRITE",
      lookFor: ["Non-default shares (backups, profiles, dev)", "READ/WRITE permissions", "Anything unusual beyond ADMIN$/C$/IPC$"],
      commonMistakes: ["Assuming null session failing means SMB is a dead end — try guest and any creds you find"],
      risk: "low",
      next: "Spider readable shares for interesting files.",
      tags: ["smb", "shares", "null-session"],
    },
    {
      id: "smb-smbclient-list",
      command: "smbclient -N -L //<TARGET>/",
      platform: "any",
      purpose: "List shares with smbclient (alternative to NetExec).",
      why: "A second tool confirms results and works when one is unavailable.",
      flags: [
        { flag: "-N", meaning: "No password (null session)" },
        { flag: "-L", meaning: "List shares" },
      ],
      lookFor: ["Share names", "Disk vs IPC vs Printer"],
      risk: "low",
      next: "Connect to an interesting share and browse.",
      tags: ["smb", "smbclient"],
    },
    {
      id: "smb-spider",
      command: "nxc smb <TARGET> -u <USER> -p <PASS> -M spider_plus",
      platform: "kali",
      purpose: "Recursively list files across readable shares.",
      whenToUse: "Once you have any working credentials (or null read access).",
      why: "Manually browsing is slow. Spidering surfaces file names across all shares so you can spot config files, scripts, and backups fast.",
      lookFor: ["*.config / *.xml / *.ps1 with credentials", "unattend.xml / sysprep", "KeePass .kdbx", "id_rsa / .ppk"],
      risk: "low",
      next: "Download and read interesting files; extract any credentials.",
      tags: ["smb", "spider", "files"],
    },
    {
      id: "smb-enum4linux",
      command: "enum4linux-ng -A <TARGET>",
      platform: "kali",
      purpose: "Comprehensive SMB/RPC enumeration: users, groups, shares, policy.",
      why: "One command aggregates many RPC/SMB queries — useful for users and password policy on domain hosts.",
      flags: [{ flag: "-A", meaning: "All simple enumeration" }],
      lookFor: ["User list (feeds password spraying)", "Password policy / lockout threshold", "Domain SID", "Groups"],
      risk: "low",
      next: "Users + policy → careful password spraying or AS-REP roasting.",
      tags: ["smb", "enum4linux", "rpc", "users"],
    },
    {
      id: "smb-rid-cycle",
      command: "nxc smb <TARGET> -u <USER> -p <PASS> --rid-brute",
      platform: "kali",
      purpose: "Enumerate domain users/groups by cycling RIDs.",
      whenToUse: "With any valid credential, to build a user list even when other enumeration is locked down.",
      why: "RID cycling reliably produces a user list, which is the raw material for spraying, roasting, and BloodHound.",
      lookFor: ["Domain users", "Service accounts (svc-*)", "Privileged groups"],
      risk: "low",
      next: "Feed users into the Active Directory workflow.",
      tags: ["smb", "rid", "users", "ad"],
    },
  ],
  lookFor: [
    "Domain name and DC role",
    "Null/guest share access",
    "SMB signing disabled (relay potential)",
    "Credentials or keys inside shares",
    "User lists and password policy",
  ],
  branches: [
    {
      condition: "Host is domain-joined (domain shown, DC ports open)",
      outcome: "Treat this as Active Directory — pivot to LDAP/Kerberos enumeration and BloodHound.",
      goto: { type: "lesson", id: "ad-smb" },
    },
    {
      condition: "You have valid credentials and get 'Pwn3d!' / admin",
      outcome: "Admin over SMB usually means code execution — proceed to initial access carefully and within scope.",
      goto: { type: "phase", id: "initial_access" },
      risk: "high",
    },
    {
      condition: "Readable share contains a credential file",
      outcome: "Extract the credential, record it, and test reuse across services (SMB, WinRM, RDP, web).",
      goto: { type: "lesson", id: "creds-reuse" },
    },
  ],
  commonMistakes: [
    "Only trying null session and giving up — reuse any creds you find",
    "Ignoring SMB signing status, which matters for relaying",
    "Not recording the domain name, which drives all AD enumeration",
  ],
  relatedLessons: ["svc-smb", "ad-smb", "creds-reuse"],
  keywords: ["smb", "445", "139", "netexec", "nxc", "smbclient", "enum4linux", "shares", "microsoft-ds"],
};
