import type { ServiceModule } from "@/types";

export const ldapModule: ServiceModule = {
  id: "ldap",
  name: "LDAP",
  ports: [389, 636, 3268, 3269],
  category: "network",
  tagline: "The Active Directory database, queryable — sometimes anonymously.",
  what: "Lightweight Directory Access Protocol serves the directory. In AD it holds users, groups, computers, group policy, and rich attributes.",
  why: "LDAP is the map of a Windows domain. Read access — even anonymous or with a low-privilege account — lets you enumerate every principal and feed BloodHound to find attack paths.",
  objective: "Read the naming context, enumerate users/groups/computers, and identify interesting attributes (SPNs, descriptions with passwords, AS-REP-roastable accounts).",
  risk: "low",
  commands: [
    {
      id: "ldap-namingcontext",
      command: "ldapsearch -x -H ldap://<TARGET> -s base namingcontexts",
      platform: "kali",
      purpose: "Discover the directory's base DN (naming context).",
      why: "You need the base DN (e.g. DC=corp,DC=local) to scope all further queries.",
      flags: [
        { flag: "-x", meaning: "Simple auth (anonymous here)" },
        { flag: "-s base", meaning: "Search the root DSE only" },
      ],
      exampleOutput: "namingContexts: DC=corp,DC=local",
      lookFor: ["Base DN", "Whether anonymous bind is allowed at all"],
      risk: "low",
      next: "Query users and groups under the discovered base DN.",
      tags: ["ldap", "389", "namingcontext"],
    },
    {
      id: "ldap-users",
      command:
        "ldapsearch -x -H ldap://<TARGET> -b 'DC=corp,DC=local' '(objectClass=user)' sAMAccountName description",
      platform: "kali",
      purpose: "Enumerate user accounts and their descriptions.",
      why: "Descriptions sometimes literally contain passwords; the account list drives spraying and roasting.",
      lookFor: ["sAMAccountName list", "Passwords in description fields", "Service accounts"],
      risk: "low",
      next: "Feed users to BloodHound / roasting.",
      tags: ["ldap", "users", "ad"],
    },
    {
      id: "ldap-nxc",
      command: "nxc ldap <TARGET> -u <USER> -p <PASS> --asreproast asrep.txt --kerberoast kerb.txt",
      platform: "kali",
      purpose: "Use NetExec to pull AS-REP-roastable and Kerberoastable accounts.",
      whenToUse: "With any valid domain credential (or for AS-REP, sometimes without).",
      why: "These accounts yield crackable hashes offline — a common route to more privilege.",
      lookFor: ["Accounts with 'Do not require Kerberos preauth'", "SPN-bearing service accounts"],
      risk: "medium",
      next: "Crack retrieved hashes offline with hashcat.",
      tags: ["ldap", "asrep", "kerberoast", "nxc"],
    },
  ],
  lookFor: ["Anonymous bind allowed", "Base DN", "User/group/computer objects", "SPNs and AS-REP-roastable accounts", "Passwords in descriptions"],
  branches: [
    {
      condition: "You can read the directory",
      outcome: "Collect data for BloodHound to reveal attack paths to Domain Admin.",
      goto: { type: "lesson", id: "ad-bloodhound" },
    },
    {
      condition: "You retrieved roastable hashes",
      outcome: "Crack offline; a cracked service-account password often unlocks lateral movement.",
      goto: { type: "lesson", id: "ad-kerberos" },
      risk: "medium",
    },
  ],
  relatedLessons: ["svc-ldap", "ad-ldap", "ad-bloodhound", "ad-kerberos"],
  keywords: ["ldap", "389", "636", "ad", "bloodhound", "kerberoast", "asrep"],
};

export const rdpModule: ServiceModule = {
  id: "rdp",
  name: "RDP",
  ports: [3389],
  category: "remote",
  tagline: "Graphical Windows access — direct, when you have valid credentials.",
  what: "Remote Desktop Protocol provides an interactive Windows desktop. Network Level Authentication (NLA) usually requires valid credentials up front.",
  why: "With working credentials, RDP is often the cleanest interactive access to a Windows host. Without them it's not an entry point — mind account lockout when testing.",
  objective: "Check whether discovered credentials grant RDP, and whether the account is privileged.",
  risk: "medium",
  commands: [
    {
      id: "rdp-check",
      command: "nxc rdp <TARGET> -u <USER> -p <PASS>",
      platform: "kali",
      purpose: "Test whether a credential can authenticate over RDP.",
      why: "Quickly confirms access without opening a full GUI session, and flags admin.",
      exampleOutput: "RDP  10.10.10.10  3389  HOST  [+] corp.local\\jdoe:Password1 (Pwn3d!)",
      lookFor: ["[+] valid login", "(Pwn3d!) = admin", "NLA required or not"],
      commonMistakes: ["Spraying RDP and triggering lockouts"],
      risk: "medium",
      next: "If valid, connect interactively with xfreerdp.",
      tags: ["rdp", "3389", "nxc"],
    },
    {
      id: "rdp-connect",
      command: "xfreerdp /u:<USER> /p:<PASS> /v:<TARGET> /cert:ignore /dynamic-resolution",
      platform: "kali",
      purpose: "Open an interactive RDP session.",
      why: "A desktop session lets you operate as the user and enumerate from inside Windows.",
      flags: [
        { flag: "/cert:ignore", meaning: "Accept the self-signed cert (labs)" },
        { flag: "/dynamic-resolution", meaning: "Resize the session cleanly" },
      ],
      lookFor: ["Desktop loads", "Which user/privileges you have"],
      risk: "medium",
      next: "Begin Windows post-exploitation enumeration.",
      tags: ["rdp", "xfreerdp"],
    },
  ],
  lookFor: ["Whether creds authenticate", "Admin vs standard user", "NLA requirement"],
  branches: [
    {
      condition: "Credentials grant an interactive session",
      outcome: "You have Windows access — enumerate user, privileges, and escalation paths.",
      goto: { type: "phase", id: "post_exploitation" },
      risk: "high",
    },
  ],
  commonMistakes: ["Password spraying RDP without checking the lockout policy first"],
  relatedLessons: ["svc-rdp", "win-enum"],
  keywords: ["rdp", "3389", "xfreerdp", "remote desktop"],
};

export const winrmModule: ServiceModule = {
  id: "winrm",
  name: "WinRM",
  ports: [5985, 5986],
  category: "remote",
  tagline: "Scriptable Windows shell — a clean foothold with the right creds.",
  what: "Windows Remote Management runs PowerShell remoting over HTTP(S). With credentials for a permitted account, evil-winrm gives a stable interactive shell.",
  why: "WinRM is a favorite because evil-winrm is reliable and quiet, supports uploads/downloads, and yields a real PowerShell session — far nicer than a reverse shell.",
  objective: "Confirm which credentials can use WinRM (Remote Management Users / Administrators) and obtain a shell.",
  risk: "medium",
  commands: [
    {
      id: "winrm-check",
      command: "nxc winrm <TARGET> -u <USER> -p <PASS>",
      platform: "kali",
      purpose: "Test WinRM access for a credential.",
      why: "Tells you if the account is allowed to use WinRM before you try to get a shell.",
      exampleOutput: "WINRM  10.10.10.10  5985  HOST  [+] corp.local\\svc-web:Summer2024! (Pwn3d!)",
      lookFor: ["[+] valid", "(Pwn3d!) = shell available"],
      risk: "medium",
      next: "Get a shell with evil-winrm.",
      tags: ["winrm", "5985", "nxc"],
    },
    {
      id: "winrm-evil",
      command: "evil-winrm -i <TARGET> -u <USER> -p <PASS>",
      platform: "kali",
      purpose: "Open an interactive PowerShell session over WinRM.",
      why: "A full shell to enumerate and, if needed, escalate — with built-in upload/download.",
      flags: [
        { flag: "-i", meaning: "Target IP" },
        { flag: "-S", meaning: "Use HTTPS (5986)" },
      ],
      lookFor: ["PS prompt", "whoami /priv output"],
      risk: "medium",
      next: "Stabilized shell — enumerate the host (Windows post-exploitation).",
      tags: ["winrm", "evil-winrm", "shell"],
    },
  ],
  lookFor: ["Which accounts can use WinRM", "Whether the shell is admin", "Privileges via whoami /priv"],
  branches: [
    {
      condition: "You got an evil-winrm shell",
      outcome: "Stabilize, then enumerate for privilege escalation.",
      goto: { type: "phase", id: "post_exploitation" },
      risk: "high",
    },
  ],
  relatedLessons: ["svc-winrm", "win-enum", "win-privesc"],
  keywords: ["winrm", "5985", "5986", "evil-winrm", "powershell", "remoting"],
};
